### ISSUE TITLE
Duda Fp-Growth y del control 2 (Tarea 1)

### ISSUE THREAD

**Issue by Pipelao** [IIC2433/Syllabus-2020-2#10]
Hola!!

Esperando que se encuentren bien, quisiera hacer una pregunta acerca del algoritmo FP-Growth que me surgió y que aún tengo en el control. Una vez que ya se construye el árbol y se deben encontrar los _Conditional Frequent Pattern Tree._ En la imagen adjunto lo que me resultó de los datos del control.

![Control 2-6-1](https://user-images.githubusercontent.com/26421921/93506188-4b75b200-f8f2-11ea-98b0-2548e1a25d23.jpg)

No sé si llegué mal al _Conditional Pattern Base_ o hay alguna regla cuando no todos coinciden, porque por lo que tengo entendido para calcular _Conditional Frequent Pattern Tree_, hay que tomar los _sets_ de elementos que son comunes en todos los caminos en el _Conditional Pattern Base_ de un item y luego calcular el soporte sumando. ¿Qué había que hacer en el caso del item A?

Gracias de antemano y espero que me puedan responder hoy porque de seguro me sirve en la tarea :)

**Comment by Jiruiz2** [comment]
Hola,

Primero que todo te pido disculpas por no haber podido responder antes pero tu pregunta calzó con el fin de semana del 18 y la semana de receso.

El procedimiento que realizas es correcto, es decir, luego de construir el árbol que tienes en la parte de arriba de tu imagen debes revisar todos los caminos que te permiten llegar a un posible item y con qué frecuencia se "llega" a este. Luego debes revisar entre **todos** estos caminos cuales items se repiten lo suficiente como para pasar el support, con lo que consigues el conditional FP-tree. Ahora bien, si hay un caso en que los caminos no tienen ningún item que logre el support, simplemente se queda vacía esa celda del conditional FP-tree, por lo que al momento de calcular todas las posibles combinaciones, en realidad solo queda el item mismo, que en este caso sería "A".

Saludos.

**Comment by sebacarrasco** [comment]
Hola @Jiruiz2 una duda, el ejemplo de arriba no debería quedar {B,A} también? porque igual B aparece 3 veces en los cpb de A

**Comment by Pipelao** [comment]
Perfecto @Jiruiz2 , gracias. Me queda la duda de qué me sirve la A sola, porque no se pueden generar reglas de asociación solo con A o si??

**Comment by Jiruiz2** [comment]
@sebacarrasco @Pipelao 
Me equivoque al explicar la elección del conditional FP-Tree anterior así que les pido que la revisen de nuevo, ya que le realicé la edición correspondiente.




> Hola @Jiruiz2 una duda, el ejemplo de arriba no debería quedar {B,A} también? porque igual B aparece 3 veces en los cpb de A

No recuerdo bien ahora cual era el support mínimo en el control, pero si era 3, entonces queda lo siguiente:

- D - {B:4, E:3}
- A - {B:3}
- E - {B:5}

> Perfecto @Jiruiz2 , gracias. Me queda la duda de qué me sirve la A sola, porque no se pueden generar reglas de asociación solo con A o si??

Si se da este caso solo significa que no debes realizar combinaciones sobre este item. Por otro lado, es importante que recuerdes que el support de itemsets de tamaño 1 es necesario para el calculo de la confianza y lift.

Por último, es importante que recuerden que al combinar dos elementos del conditional fp-tree, el resultado siempre debe tener el support mínimo entre las opciones, como se puede apreciar en la siguiente imagen:

![image](https://user-images.githubusercontent.com/26437497/93950514-10241a80-fd1a-11ea-910c-2b21f8c8ebc6.png)

**Comment by Pipelao** [comment]
Yaa perfect @Jiruiz2 , creo que de a poco le estoy agarrando la onda, xD. 

Tengo una duda que me surge con el ejemplo del cuaderno que mandé como imagen. Para el elemento D, si el camino {B,A:3}, de forma que cumpla con el soporte mínimo, se generaría: {B:6,E:3,A:3}, entonces se puede generar {B,E,A} por ejemplo? Porque por matemática creo que funciona, sin embargo el camino {B -> E -> A} tiene soporte 1. ¿En qué me estoy equivocando?

Gracias :)

**Comment by Jiruiz2** [comment]
> Yaa perfect @Jiruiz2 , creo que de a poco le estoy agarrando la onda, xD.
> 
> Tengo una duda que me surge con el ejemplo del cuaderno que mandé como imagen. Para el elemento D, si el camino {B,A:3}, de forma que cumpla con el soporte mínimo, se generaría: {B:6,E:3,A:3}, entonces se puede generar {B,E,A} por ejemplo? Porque por matemática creo que funciona, sin embargo el camino {B -> E -> A} tiene soporte 1. ¿En qué me estoy equivocando?
> 
> Gracias :)

Creo que estas mezclando un poco las cosas, ya que cuando realizas las combinaciones luego de haber obtenido el Conditional FP-Tree, ya no importan los caminos, sino que la frecuencia en conjunto, por lo que para el elemento D nos queda {B:4, E:3}, por lo tanto las combinaciones son:
- {D, B: 4}
- {D, E: 3}
- {D, E, B: 3}

**Comment by Pipelao** [comment]
Ahh ok, te entiendo @Jiruiz2 , gracias.
