### ISSUE TITLE
[T3] Encoding columnas categoricas

### ISSUE THREAD

**Issue by danustilovsky** [IIC2433/Syllabus-2020-2#100]
Hola, me preguntaba si habia algun metodo de encoding que fuera preferible al momento de utilizar algoritmos de clustering? Habia pensado en one hot encoding, pero  me preocupa el aumentar mucho el numero de columnas dado que el dataset es bastante extenso. Utilizar otros metodos es correcto?

Muchas gracias!

**Comment by AstridESMJ** [comment]
¡Hola!

Como hemos visto en las ayudantías sklearn posee varios métodos de encoding, en la ayudantía vimos uno en particular. Puedes revisar las ayudantías para ver qué encoding usar o revisar la documentación de sklearn, es parte de la tarea decidir estos pasos y justificarlos.

Saludos,

Astrid
