### ISSUE TITLE
Calculo distancias

### ISSUE THREAD

**Issue by IvaniaArias** [IIC2433/Syllabus-2020-2#103]
Holaa! 
Quería consultar si al momento de calcular distancias se puede ocupar la libreria sklearn o similares.
Gracias de antemano!

**Comment by Hernan4444** [comment]
Hola,

El cálculo de distancia es parte de la implementación del algoritmo y en ese solo se puede ocupar numpy y pandas. Si encuentras, dentro de esas 2 librerías, alguna función que permita calcular distancias, entonces no hay problema 👍 . En otro caso será neceasrio que la implementes tu porque no se puede usar otra librería aparte de esas 2 para lo que pides.

Saludos :v:
