### ISSUE TITLE
Justificación preprocesamiento

### ISSUE THREAD

**Issue by sebacarrasco** [IIC2433/Syllabus-2020-2#105]
Por el tema de las 5 líneas, en la parte del preprocesamiento se puede escribir con más detalle la justificación de este y en la parte de análisis más resumido y general?

**Comment by Hernan4444** [comment]
Hola,

Si se puede 👍 , pero solo para la parte del preprocesamiento. Las demás preguntas deben mantenerse en un máximo de 5 líneas.

Saludos :v:
