### ISSUE TITLE
T3 - Cuándo realizar subsampling

### ISSUE THREAD

**Issue by fguinez** [IIC2433/Syllabus-2020-2#109]
Si deseo realizar _subsampling_, **¿hay algún problema con que lo realice dentro de la función de preprocesamiento?** (por ejemplo, que necesiten el _dataset_ preprocesado completo para la corrección).

Por otro lado, no logro decidir si **¿es más efectivo realizar el _subsampling_ antes o después de normalizar los datos?**. Antes de normalizar, ajustaría la normalización mejor al _subsampling_ pero no sería tan fiel al _dataset_ completo. Después de normalizar, mantendría una normalización fiel al _dataset_ completo pero podría tener atributos con rangos de valores más bajos.

**Comment by AstridESMJ** [comment]
¡Hola!

No hay problema que vaya dentro de la función de preprocesamiento, si debes indicar claramente que está incorporada esta tarea y dar la opción de no hacer subsampling.
Te recomiendo dar la opción de subsampling después de terminar todo el preprocesamiento, es decir primero dejas listo el dataset incluida la normalización y luego se hace el subsampling.

Saludos,

Astrid

**Comment by fguinez** [comment]
gracias!
