### ISSUE TITLE
Duda exportación archivos

### ISSUE THREAD

**Issue by pazanelli** [IIC2433/Syllabus-2020-2#11]
Hola! En la tarea 1 desde donde debemos importar los csv? los podemos copiar nuestro repositorio?

**Comment by fedetaladriz** [comment]
Hola! 
Si, deben importar el dataset localmente, por lo que si te acomoda, puedes copiar los `.csv` en tu mismo repo local. Sin embargo, deben tener cuidado con **NO subir los archivos `.csv` a github** cuando hagan push. Te recomiendo tener un archivo `.gitignore` para que no se agreguen al momento de hacer commit. 
Saludos!
