### ISSUE TITLE
Duda creación de árbol recursiva 

### ISSUE THREAD

**Issue by FloValdes** [IIC2433/Syllabus-2020-2#12]
Hola, tengo una duda sobre la parte que dice que el árbol debe ser generado recursivamente. A qué se refiere exactamente? El algoritmo que vimos en la ayudantía iteraba sobre los sets de items de los usuarios, debemos pensar en una nueva manera de hacer lo mismo pero con recursión? Gracias.

**Comment by fedetaladriz** [comment]
Hola @FloValdes !
Quizás esto no quedó tan claro en el enunciado. Con esa parte nos referimos a que el árbol en sí tiene que ser recursivo, en el sentido de que cada nodo del árbol es un objeto tipo `node`, el que contiene una lista con sus hijos (que también son clase `node`) y así sucesivamente. La creación de este árbol, sin embargo, no tiene que ser necesariamente recursiva; también puede ser iterativa. Espero que quede mas claro ahora. 
Saludos!

**Comment by FloValdes** [comment]
Perfecto, gracias!
