### ISSUE TITLE
Duda minar fp tree

### ISSUE THREAD

**Issue by FloValdes** [IIC2433/Syllabus-2020-2#13]
Hola, tengo una duda de cómo se crea el conditional fp tree. Teniendo todos los caminos que llegan a un item X, qué se debe hacer ahora? En la ayudantía como eran pocos caminos solo lo veíamos al ojo y decíamos que estos items se repetían lo suficiente para superar el soporte, pero cuando tenemos cientos de caminos no sé cómo es la manera oficial del algoritmo para sacar esos subconjuntos (probar todas las combinaciones? usar el algoritmo a priori?).

Gracias!

**Comment by sebacarrasco** [comment]
Hola @FloValdes ! pudiste encontrar solución en otra parte? Estoy con la misma duda

**Comment by FloValdes** [comment]
@sebacarrasco  no :( busqué ejemplos pero como que todos lo hacían al ojo

**Comment by sebacarrasco** [comment]
Por si te sirve, encontré este [video](https://www.youtube.com/watch?v=UDpK_pgsZZY) en el que lo hacen más metódicamente... no sé si será la forma óptima pero es lo mejor que he encontrado

**Comment by Jiruiz2** [comment]
Hola,

Lamentablemente no te puedo dar una respuesta específica, ya que es parte de la tarea que piensen en como solucionar ese problema, es decir, se espera que piensen en una manera de almacenar todos los caminos para cada item y luego poder revisar entre todos estos caminos los elementos que tienen en común de una manera automática, ya que, como mencionas, no es factible hacerlo "al ojo".

Saludos.
