### ISSUE TITLE
Agregar más preprocesamiento

### ISSUE THREAD

**Issue by mora4** [IIC2433/Syllabus-2020-2#14]
Hola,

Tengo una duda, puedo agregar mas preprocesamiento del que dice el enunciado? Por ejemplo estaba pensando filtrar según soporte antes de hacer el ndarray, es posible?

Gracias!

**Comment by Hernan4444** [comment]
Hola, 

El filtro se debe incluir dentro del algoritmo y no como un paso previo en el pre-procesamiento. 

Saludos :v:

**Comment by absoto4** [comment]
Hola, y puedo hacer le filtro antes de mandar a crear el fp-tree? técnicamente igual sería dentro del algoritmo, pero no en la parte que dicen en el enunciado.
Saludos

**Comment by Hernan4444** [comment]
Hola,

No, debe estar dentro del algoritmo como se pide en el enunciado puesto que en el proceso de construir y árbol de minar se tendrá que volver a filtrar. Recomiendo revisar el ejercicio de ejemplo para ver que hay ciertos filtros durante el minado.

Saludos :v:
