### ISSUE TITLE
[Tarea 1] Dudas sobre los atributos de las clases solicitadas

### ISSUE THREAD

**Issue by arpincheira** [IIC2433/Syllabus-2020-2#15]
Hola, quería saber dos cosas:

1. La clase Fpgrowth puede almacenar dentro de si misma una que otra variable o sería ideal que no fuera así?
2. La clase Node, debe si o si tener una lista con sus hijos? No puede ser otro tipo de estructura que ofrezca Python y que permita acceder con mayor velocidad a ciertos índices? Esta pregunta va enfocada más que nada a lo que dice el enunciado:
<img width="1130" alt="Captura de Pantalla 2020-09-22 a la(s) 18 32 57" src="https://user-images.githubusercontent.com/37157550/93940280-92084980-fd02-11ea-8f7f-fde1ed1b23f8.png">

De antemano muchas gracias

**Comment by Jiruiz2** [comment]
Hola,
1. Tu decides como implementas la clase, así que puedes utilizar las variables que quieras.
2. Puedes utilizar cualquier estructura que estimes conveniente para los hijos
