### ISSUE TITLE
Orden itemsets mine_tree

### ISSUE THREAD

**Issue by sebacarrasco** [IIC2433/Syllabus-2020-2#16]
Hola, quería saber si es que es necesario que los itemsets que se retornan en la función mine_tree estén de forma ordenada por su soporte. Entiendo que este orden es importante para la creación del árbol, pero creo que no debería ser importante para la generación de reglas de asociación. (Pregunto esto porque lo que retorno es una lista de sets)

**Comment by fedetaladriz** [comment]
Hola @sebacarrasco !
No, no es necesario que se retornen ordenados. Lo único importante es que cumplan con el mínimo de soporte. 
Saludos!
