### ISSUE TITLE
¿Es necesario atributo hijos en clase Node?

### ISSUE THREAD

**Issue by Pipelao** [IIC2433/Syllabus-2020-2#17]
Hola, espero que se encuentren bien.

Quiero preguntar acerca del atributo hijos para la clase _Node_, ¿es necesario implementarlo? Porque de acuerdo a lo que mencionan en esta página: https://dzone.com/articles/machinex-understanding-fp-tree-construction, pienso hacer eso del node link para cada elemento frecuente, entonces pensaba recorrer cada ruta de "abajo hacia arriba", siendo así sólo necesario tener el padre de cada nodo, que sería como el reemplazo del atributo hijos, ¿es legal hacer esto?

Gracias de antemano.

**Comment by Hernan4444** [comment]
Hola,

No hay problema con lo que pides (es legal)

Saludos :v:
