### ISSUE TITLE
¿En qué sección debe utilizarse la base de datos movies.csv?

### ISSUE THREAD

**Issue by Pipelao** [IIC2433/Syllabus-2020-2#18]
Hola de nuevo, xD.

No me queda claro en qué sección de las actividades que se mencionan en el enunciado debemos utilizar la base de datos _movies.csv_, ¿será en la sección 3 o 4?

Gracias.

**Comment by fedetaladriz** [comment]
Hola @Pipelao ! 
En ambas 😄, es decir, debes obtener las reglas de asociación de la base de datos una vez (o mas de una vez si quieres cambiar alguno de los parámetros: `min_support`, `lift` o `confidence`) y luego hacer las actividades de estas dos partes. Lo importante es que en las partes 1 y 2 constan de solo implementar las funciones y clases que ahí se especifican, y una vez hecho esto, aplicas el algoritmo sobre la BDD entregada para hacer las partes 3, 4, 5 y 6. 
Saludos!

**Comment by Pipelao** [comment]
Ok, entiendo que son para todas las actividades restantes; ¿entonces no debo mostrar la regla de asociación entre `id's` de películas sino que sólo entre géneros de películas?, ¿o debo entregar ambas reglas de asociaciones?

**Comment by fedetaladriz** [comment]
El algoritmo te debe retornar asociaciones entre id's de películas. El nombre te servirá para poder darles sentido (ya que no entenderás mucho si solo ves asociaciones entre id's) y para explicarlas en la parte 4. También te puedes apoyar en el género si crees que te ayuda en la explicación.

**Comment by Pipelao** [comment]
Perfecto @fedetaladriz , gracias.
