### ISSUE TITLE
[T1] parámetros de métodos

### ISSUE THREAD

**Issue by fnquinteros** [IIC2433/Syllabus-2020-2#19]
Hola! quería saber si los parámetros que reciben los métodos mencionados en el enunciado son obligatorios por temas de formato y cómo se evaluará la tarea o si se pueden cambiar (agregar, quitar, etc).

Saludos!

**Comment by fedetaladriz** [comment]
Hola @fnquinteros ! 
Los parámetros especificados en el enunciado son los mínimos. Sin embargo, pueden agregar mas parámetros si lo consideran necesario, pero deben tener valores por defecto. Si no se respeta este formato se descontará puntaje. 
Saludos!
