### ISSUE TITLE
Problemas con instalación de jupyter

### ISSUE THREAD

**Issue by Zapararte** [IIC2433/Syllabus-2020-2#2]
Hola! Tengo problemas para instalar jupyter notebook, mi SO es Windows, y siento que el problema se da porque tengo una SDD y un HDD y me queda la embarrada con los path. Hice el install jupyter, luego quise ejecutarlo (desde esa misma consola) y no me dejó. Investigué y agregué (o eso creo) su ruta al path, de esa forma logré ejecutarlo pero me tira el error:
![image](https://user-images.githubusercontent.com/31223470/91212123-cece2a00-e6dd-11ea-9057-08b9fdfba97c.png)

Ya sea que lo ejecute desde la consola de comandos o powershell me tira el mismo error.

**Comment by Hernan4444** [comment]
Hola, en primero lugar, intentaste con `pip install notebook` que no recuerdo hacer install jupyter. Cuentame cómo te va con ese pip y luego escribir `jupyter notebook` en la consola.

Saludos :v:

**Comment by Zapararte** [comment]
Eso mismo! de verdad usé "pip install notebook". Cuando ejecuto esos comandos la consola me dice primero que ya está instalado jupyter, y al ejecutar "jupyter notebook" me aparece el mismo código de error.

**Comment by Zapararte** [comment]
Un amigo me recomendó desinstalar jupyter (no sé si debería desinstalar python también) e instalar anaconda, ¿es esto recomendable?

**Comment by Hernan4444** [comment]
Oka, ¿puedes compartir un pantallazo de tu consola luego de que haces `jupyter notebook`?

Sobre Anaconda, no lo recomendamos porque la experiencia nos ha mostrado que varios alumnos la pasan mal con la instalación de librerías en anaconda.

**Comment by Zapararte** [comment]
![image](https://user-images.githubusercontent.com/31223470/91648345-5eecd600-ea34-11ea-9fa9-9c4dfe0c73de.png)

Probaré desinstalar y volver a instalar jupyter, para ver si se corrige el error.
