### ISSUE TITLE
10 mejores reglas

### ISSUE THREAD

**Issue by sebacarrasco** [IIC2433/Syllabus-2020-2#20]
Hola, una duda: para las 10 mejores reglas el segundo criterio sería como para un desempate verdad? onda si tienen igual el primer criterio entonces se compara el segundo?

**Comment by fedetaladriz** [comment]
Hola @sebacarrasco !
Los criterios pueden aplicarlos como quieran, ya sea los dos al mismo tiempo (como tu dices, utilizando el segundo para desempatar en caso de iguadad en el primero), o por separado (es decir, entregar dos listas de 10 mejores reglas, una por cada criterio). **Lo importante es que tengan dos criterios distintos**  y que den una explicación razonable de por qué las eligieron. 
Saludos!

**Comment by arpincheira** [comment]
Hola, me entra la duda con respecto a estos criterios, los criterios pueden ser comparaciones según indicadores ya existentes en reglas de asociación o deben ser valores estadísticos establecidos y calculados por nostros?

**Comment by Jiruiz2** [comment]
Hola,
Asumo que te refieres a si solo deben usar lift, support y confianza o deben agregar otras métricas. Sobre esto, tienen total libertad de acción tanto para usar las 3 conocidas como para investigar y agregar otras.
Saludos
