### ISSUE TITLE
[T1] Tiempo de ejecución

### ISSUE THREAD

**Issue by fnquinteros** [IIC2433/Syllabus-2020-2#21]
Hola! cual es el tiempo de ejecución máximo que tolerarán?

Saludos!
Felipe

**Comment by Jiruiz2** [comment]
Hola,

Como referencia, la implementación por librería demora 0.8 segundos. Por otro lado, respondiendo a tu pregunta, si código no debiese demorarse más de 5 minutos en realizar el algoritmo.

Saludos

**Comment by fguinez** [comment]
Hola! Esos 5 minutos son considerando cualquier valor de `min_support`?

En general mi implementación demora menos de 5 minutos, pero para valores de `min_support` muy pequeños (<0.1) los tiempos de ejecución se disparan😢

**Comment by Hernan4444** [comment]
Hola,

Para valores iguales o sobre 0.1, para más chicos se demora mucho más así que ahí seremos permisivos.

Saludos ✌️
