### ISSUE TITLE
[Tarea1] Soporte mínimo: decimal o entero?

### ISSUE THREAD

**Issue by arpincheira** [IIC2433/Syllabus-2020-2#22]
Hola, tengo una duda con respecto al tipo de dato al que correspondería el soporte mínimo, resulta ser que en distintas partes, se ha definido el soporte mínimo como un número decimal correspondiente a una fracción de lo que vendría siendo el total de transacciones. El problema viene siendo ahora con la guía que acaban de subir en donde se entiende que el soporte mínimo es un **entero**, por lo que me entra la duda hacerca del valor que se va a ocupar al momento de la evaluación, si un entero o un valor decimal.

Muchas gracias de antemano

**Comment by fedetaladriz** [comment]
Hola @arpincheira ! 
Efectivamente a veces se considera entero y otras se considera decimal (una proporción del número de transacciones). Si revisan las distintas fuentes de internet, se hace de ambas formas. Sin embargo, en la tarea les pediremos que lo **consideren decimal**, para que no dependa del total de transacciones. De esta manera se ahorrarán problemas si, por ejemplo, aplican el algoritmo a una muestra del dataset completo (ya que tiene un tamaño menor).
Saludos!

**Comment by FloValdes** [comment]
Hola @fedetaladriz, tengo una duda respecto a esto cuando dices que nos ahorraremos problemas si aplican el algoritmo a una muestra del dataset. Digamos que estoy viendo un subconjunto del dataset (que tiene 50 observaciones) con 5 observaciones, debería cambiar el 'total' para calcular el soporte a 5 o se debería dejar fijo en el total original de 50?

**Comment by fedetaladriz** [comment]
> Hola @fedetaladriz, tengo una duda respecto a esto cuando dices que nos ahorraremos problemas si aplican el algoritmo a una muestra del dataset. Digamos que estoy viendo un subconjunto del dataset (que tiene 50 observaciones) con 5 observaciones, debería cambiar el 'total' para calcular el soporte a 5 o se debería dejar fijo en el total original de 50?

Hola @FloValdes , me refiero a que si usas un `min_support` entero, y le pones, por ejemplo, = 5,  la "exigencia del umbral" va a depender de el tamaño del dataset que le entregues al algoritmo. Por ejemplo, si el dataset es de tamaño 10, es muy exigente, puesto que un elemento tiene que estar en al menos la mitad de las transacciones del dataset para pasar el umbral, mientras que si el dataset es de tamaño 100, solo basta con que el elemento esté en un 5% de las transacciones, lo que es poco restrictivo. **En resumen: No se compliquen y consideren que el parámetro `min_support` es decimal (proporción del dataset).**
Saludos!
