### ISSUE TITLE
Subconjuntos de itemsets frecuentes

### ISSUE THREAD

**Issue by mora4** [IIC2433/Syllabus-2020-2#23]
Hola!

La clase de FP dice:

> Para cada itemset frecuente sacar sus subconjuntos y
calcular la confianza entre ellas.

Pero me queda la duda si son **todos** los subconjuntos o solo las **particiones**. Por ejemplo con el itemset frecuente {A, B, C} :
Las posibles reglas con todos los subconjuntos son:
- A -> B
- A -> C
- B -> A
- B -> C
- C -> A
- C -> B
- A, B -> C
- A, C -> B
- B, C -> A
- C -> A, B
- B -> A, C
- A -> B, C

Las posibles reglas con las particiones son:
- A, B -> C
- C -> A, B
- A, C -> B
- B -> A, C
- B, C -> A
- A -> B, C

¿Cual es la forma correcta de generar las posibles reglas de asociacion?

Gracias!

**Comment by Jiruiz2** [comment]
Hola,

Es lo primero que planteas. 

Saludos

**Comment by santilaguna** [comment]
@Jiruiz2 es necesario que si tengo A, B -> C y A, B -> D también revise el caso A, B -> C, D, dado que la última regla sólo se puede cumplir si las dos primeras se cumplen sería aumentar la complejidad sin ninguna ganancia de información. Podemos obviar estos casos?

**Comment by Jiruiz2** [comment]
Hola,

En base a lo que planteas hay dos casos:

- A, B -> C y A, B -> D pasan el support y confianza mínimos, por lo tanto si es necesario que revises A, B -> C, D debido a que son cosas distintas, ya que los dos primeros casos te dicen que hay una probabilidad X e Y de que estén por separado si es que se encuentra A y B en un posible Itemset, mientras que  A, B -> C, D define la probabilidad Z de que C y D estén simultáneamente si es que se encuentra A y B en un itemset.

- A, B -> C y/o A, B -> D NO pasan el support y/o confianza mínimos, por lo tanto, no tiene sentido revisar A, B -> C, D, ya que en el mejor de los casos tendrá el menor support y confianza entre ambas opciones, por lo que no será aceptada como regla de asociación.

Saludos
