### ISSUE TITLE
[Tarea1] Orden de los itemsets frecuentes

### ISSUE THREAD

**Issue by arpincheira** [IIC2433/Syllabus-2020-2#24]
Hola, me surgió una duda sobre el orden en que aparecen las tuplas de itemsets frecuentes, principalmente porque mi código entrega por ejemplo que A, B es un itemset frecuente, mientras que la librería mlxtend me dice que B, A es un itemset frecuente(ambos con el mismo soporte en todo caso).  Por esto quería preguntar, importa el orden de aparición de los ítems en las tuplas de  itemsets frecuentes?

Gracias de antemano

**Comment by fedetaladriz** [comment]
Hola @arpincheira !
Para un itemset, lo importante es en cuantas de las transacciones del dataset se encuentran todos los elementos de este itemset y, si esta proporción supera el soporte mínimo que estableciste, se considera un itemset frecuente. Como podrás ver, aquí no es importante el orden en el que definas los elementos de este itemset. Por lo tanto, los itemsets {A, B} y {B, A} son equivalentes. 
Sin embargo, al formar las reglas de asociación SI es importante el orden (es decir, es importante cuales elementos van en el antecedente y cuales en el consecuente): Bajo el itemset frecuente {A, B}, NO son equivalentes las reglas A->B y B->A (pensar en como cambia la confianza y el _lift_ entre estas dos reglas). 
Saludos!
