### ISSUE TITLE
[Tarea 1]Estructuras permitidas

### ISSUE THREAD

**Issue by arpincheira** [IIC2433/Syllabus-2020-2#25]
Hola, estaba viendo que en el enunciado da algunos ejemplos de las estructuras que se espera que retornemos de la función mine_tree, a continuación dejo una foto del mismo:
<img width="822" alt="Captura de Pantalla 2020-09-25 a la(s) 23 43 09" src="https://user-images.githubusercontent.com/37157550/94329190-428a7d80-ff8f-11ea-8175-e583500ed238.png">

Mi pregunta con respecto a esto es, ¿Estas son las únicas opciones que tenemos o podemos retornar otras estructuras como por ejemplo un diccionario?

De antemano muchas gracias

**Comment by Hernan4444** [comment]
Hola, 

Puedes retornar otra estructura mientras no implique instalar una librería nueva para disponer de dicha estructura. Así que un diccionario está bien.

Saludos :v:

**Comment by fnquinteros** [comment]
es legal usar `defaultdict` de `collections`?

**Comment by Hernan4444** [comment]
@fnquinteros no es legal. Cómo sale en el enunciado: 

![image](https://user-images.githubusercontent.com/15641721/94753778-b220b400-0365-11eb-9f06-5f02d6e0e330.png)


Y las únicas librerías mencionadas son: numpy, pandas e itertools.

Saludos :v:
