### ISSUE TITLE
Quitar argumentos en los métodos de las clases

### ISSUE THREAD

**Issue by bjbarias** [IIC2433/Syllabus-2020-2#27]
Hola! Quería saber si podía quitarle el argumento fptree al método mine_tree de la clase Fpgrowth.

**Comment by fedetaladriz** [comment]
Hola @bjbarias !
Como se mencionó en #19 , los argumentos especificados en el enunciado son los mínimos. Si esto no se respeta, se penalizará con descuento puntaje.
Saludos!
