### ISSUE TITLE
Soporte mínimo y forma de minar árbol

### ISSUE THREAD

**Issue by Pipelao** [IIC2433/Syllabus-2020-2#28]
Hola,

Quisiera saber si existe un soporte mínimo que deberíamos considerar para correr el algoritmo. Lo que pasa, es que al colocar un soporte mínimo del 10% se me demora mucho, ¿es normal?, ¿me debería pasar o significa que mi implementación es muy ineficiente?

Y con respecto a eso, quisiera asegurarme que recorrer el árbol a fuerza bruta, digamos como Depth-First Search o Breadth-First Search cada vez que se busque el camino de un item no es la forma más eficiente, porque se recorrería el árbol por cada elemento lo que no me parece muy eficiente, es así, ¿verdad? Porque si esa es la forma entonces estoy puro perdiendo el tiempo al implementarlo de otra, xD.

**Comment by fedetaladriz** [comment]
Hola @Pipelao !
En cuanto al tiempo de ejecución, tendremos como criterio lo indicado en #21 . En cuanto a la segunda pregunta, no puedo darte muchas pistas :( es parte de la tarea. Te recomiendo revisar nuevamente tu algoritmo y, en especial, los loops y/o recursiones. Recuerda usar funciones de `pandas` y `numpy` (e `itertools` si no optarás al bonus) que son mas eficientes para trabajar con muchos datos. 
Saludos!

**Comment by Pipelao** [comment]
Gracias @fedetaladriz .
