### ISSUE TITLE
Retornar DataFrame en vez de fptree

### ISSUE THREAD

**Issue by Pipelao** [IIC2433/Syllabus-2020-2#29]
Hola de nuevo,

Quiero preguntar si es posible que la función _create_tree_ puede retornar un `DataFrame` que por cada item tenga sus _node_links_ como menciono en #17 y de la misma forma recibir este `DataFrame` en la función _mine_tree_, ya que al fin de cuentas en cada `node` es como un mini árbol de su propio camino.

Gracias.

**Comment by Hernan4444** [comment]
Hola,

~No hay problema con lo solicitado,~

Edit: No puedes hacer eso, debes retornar el objeto `node` como dice en el enunciado. En como guardar los itemset frecuentes damos más libertad con eso.

Saludos :v:

**Comment by Hernan4444** [comment]
Hola,

Tuve que actualizar la respuesta porque pensábamos que te referias a cómo representar los itemset, pero no era así. Debes seguir lo indicado en el enunciado respecto a retornar un objeto clase `node`.

Saludos :v:

**Comment by zaertis0** [comment]
Duda puede la función create_tree retornar 2 objetos el node y algo más (diccionario)??

**Comment by Hernan4444** [comment]
Hola,

No se puede, la función indica que retorna 1 objeto tipo node y no 2 objetos (uno tipo node y otro diccionario), pero recuerda que la objeto `node` se le pueden agregar más atributos según estimen conveniente.

Saludos :v:

**Comment by Pipelao** [comment]
Ok, gracias @Hernan4444
