### ISSUE TITLE
Dudas preprocess

### ISSUE THREAD

**Issue by Ajbarros1** [IIC2433/Syllabus-2020-2#30]
Hola! Tengo algunas dudas sobre la función preprocess:

1. El data frame que recibe es el ratings.csv transformado a data frame?
2. Cuales son las columnas innecesarias? Todas menos userId, movieId y rating?
3. Podemos utilizar la libreria pandas y todas sus funciones para esta funcion?

Gracias de antemano

**Comment by fedetaladriz** [comment]
Hola @Ajbarros1 !
1. Si, es decir, debes leer el archivo y guardar la información en un `DataFrame`. Recuerda que `pandas` tiene funciones que permiten hacer esto en una linea.
2. La idea es que pienses cuales son las columnas innecesarias de acuerdo a lo que necesites, teniendo en cuenta que quieres obtener reglas de asociación entre ids de películas. 
3. Si. 
Saludos!
