### ISSUE TITLE
Control 3

### ISSUE THREAD

**Issue by diflores** [IIC2433/Syllabus-2020-2#31]
# Dudas control 3

## Aspectos generales

5 líneas por subpregunta es suficiente, pero no deberían llegar a respuestas así de extensas.

## Pregunta 1

Basta con explicar, no se requiere mostrar cálculos matemáticos.

Las columnas son {0, 1}. Ejemplo: 0.5 podría estar dentro de los valores posibles.

## Pregunta 2

Un conjunto de entrenamiento y otro para predicción. 

## Pregunta 3

Pueden suponer valores. Por ejemplo: 3 columnas y 10 valores posibles por cada una. Basta con un ejemplo que se pueda generalizar.

## Pregunta 4

- "todo esto" = relación del concepto colinealidad con variables que dependen de otras.
- No se requiere demostración matemática.

- Las tres variables pertenecen al *data set*.

- Ejemplo: tres columnas A, B y C que pertenecen al *data set* y ocurre que A está correlacionada con C y B está correlacionada con C. Se pueden utilizar las tres para predecir una cuarta variable.

**Comment by pazanelli** [comment]
En la pregunta 1 a qué se refiere con 'eliminar el sesgo de elección' ¿a cómo elegir k? ¿o a como eliminar columnas?

**Comment by mgbriones** [comment]
puedo subir un escaner (en pdf) de mi desarrollo hecho a mano?

**Comment by Jiruiz2** [comment]
Hola, 

> En la pregunta 1 a qué se refiere con 'eliminar el sesgo de elección' ¿a cómo elegir k? ¿o a como eliminar columnas?

Es complicado responder sin darte la respuesta, pero como tip, piensa en el rango de los datos con los que estás trabajando.



> puedo subir un escaner (en pdf) de mi desarrollo hecho a mano?

No hay problema, pero asegúrate que se vea bien y se entienda todo.

**Comment by arpincheira** [comment]
En la pregunta 2, el modelo de predicción mencionado corresponde a uno cualquiera o debemos nosotros explicar/proponer un modelo de predicción a utilizar?

**Comment by Jiruiz2** [comment]
Hola, 
> En la pregunta 2, el modelo de predicción mencionado corresponde a uno cualquiera o debemos nosotros explicar/proponer un modelo de predicción a utilizar?

Corresponde a un modelo de predicción cualquiera, es decir, deben tratarlo de manera genérica.

**Comment by mgbriones** [comment]
en la pregunta 4, podemos asumir que la correlacion es 1?

**Comment by Hernan4444** [comment]
> en la pregunta 4, podemos asumir que la correlacion es 1?

No,  hay correlación positiva o negativa, pero no se puede asumir que es 1.

Saludos :v:

**Comment by lucas-valenzuela** [comment]
Hola, en la pregunta 3, la materia que se está preguntando se vio en la clase 7 de regresión lineal? O puede corresponder a la de otros días?

**Comment by mgbriones** [comment]
se puede entregar más de una vez no?

**Comment by Jiruiz2** [comment]
> Hola, en la pregunta 3, la materia que se está preguntando se vio en la clase 7 de regresión lineal? O puede corresponder a la de otros días?

 No se vio directamente, pero se puede deducir a partir de la manteria.

**Comment by Jiruiz2** [comment]
> se puede entregar más de una vez no?

Si, está habilitado para múltiples intentos
