### ISSUE TITLE
Agregar funciones

### ISSUE THREAD

**Issue by danustilovsky** [IIC2433/Syllabus-2020-2#32]
Hola, esta bien si defino varias funciones dentro de la clase fptree y las uso en las funciones que piden en el enunciado? Para que asi quede mas claro el codigo. 

Gracias!

**Comment by fedetaladriz** [comment]
Hola @danustilovsky !
Si, no hay problema. Eso si, debes documentar todos los métodos pedidos en el enunciado, por lo que, si algún método/función extra es importante para alguno de los métodos/funciones mínimas, debes explicar para que lo ocupas.
Como se menciona en el enunciado, si no hay documentación o está muy desordenado se aplicarán descuentos. 
Saludos!
