### ISSUE TITLE
duda creacion de arbol

### ISSUE THREAD

**Issue by mgbriones** [IIC2433/Syllabus-2020-2#33]
hola, tengo un problema al crear el arbol. 
Mi codigo es capaz de añadir hijo a al nodo nulo (llamemos a este nodo hijo nodo 1), y luego de forma recursiva tambien agrega un hijo al nodo 1 (llamemos a este nodo2). 
Cuando pregunto por `nodo_nulo.hijos` retorna `nodo1` .

El problema que tengo  es que cuando pregunto por:
`nodo1.hijos` retorna `{}`, siendo que deberia retornar `nodo2.`
Que puede estar ocurriendo?

Aclaracion: hijos es un atributo de la clase nodo que representa un diccionario.

**Comment by Hernan4444** [comment]
Hola,

Tal vez podrías verificar (1) que luego de agregar un hijo, efectivamente está añadiendo el nodo_2 al nodo_1 (con su print de "Nodo X agregó a Nodo Y") y luego, (2) que nodo_nulo apunte al mismo nodo_1 que antes le agregaste el nodo_2.

A veces pasa que en la parte recursiva, en vez de acceder de forma recursiva al nodo hijo, se crea un nuevo nodo. Podrías usar la función `id` que le pasas un objeto y te entrega su ID, de este modo puedes verificar que El nodo_1 que le agregaste como hijo un nodo_2 tiene el mismo id (es el mismo objeto) que el nodo_1 que agregas al nodo_nulo.

Saludos :v:
