### ISSUE TITLE
Umbral de confianza y lift

### ISSUE THREAD

**Issue by fguinez** [IIC2433/Syllabus-2020-2#34]
Hola!

En el enunciado, la explicación del método `generate_association_rules` dice que:
> Es posible entregarle umbrales de confianza o _lift_ para las reglas que se retornarán

¿Esto implica que los valores admitidos deben ser **mayor o iguales** o **estrictamente mayores** al umbral?

Un saludo✌️

**Comment by Hernan4444** [comment]
Hola, tiene que ser mayor o igual. Porque la idea es sacar items que no alcanzan un cierto umbral (son menores).

Saludos :v:
