### ISSUE TITLE
que debe ir en el jupyter?

### ISSUE THREAD

**Issue by mgbriones** [IIC2433/Syllabus-2020-2#35]
Hola, en el jupyter deben ir solamente las funciones y metodos solicitados?
Que pasa con las funciones creadas adicionalmente, deben ser importadas y justificadas, pero no ponerlas en el informe?
saludos!

**Comment by fedetaladriz** [comment]
Hola @mgbriones !
Si crees que queda mas ordenado, puedes crear las funciones en otro script e importarlas. No hay problema con eso. Como dices, solo deben recordar **justificarlas si son importantes para alguno de los métodos o funciones mínimas**. 
Saludos!
