### ISSUE TITLE
Puedo usar IPython.display?

### ISSUE THREAD

**Issue by Oisangui** [IIC2433/Syllabus-2020-2#36]
No sé si cuenta como librería, pues es usar una feature de jupyter, que permite imprimir dos dataframes en la misma celda. Lo quiero usar para no tener que usar una celda para cada dataframe, es posible?

Lo que habría en mi código es
```python3
from IPython.display import display
```

Y se usa así

```python3
df = pd.read_csv('ratings.csv')
display(df.head())
display(df.describe())
```
Lo que haría posible generar el siguiente output:

![image](https://user-images.githubusercontent.com/48262842/94965405-cb467380-04d1-11eb-89b4-88e26bda32da.png)

**Comment by vvcastro** [comment]
Hola @Oisangui! No hay problema con usar la librería de la forma que señalas!
