### ISSUE TITLE
Duda itemsets frecuentes

### ISSUE THREAD

**Issue by danustilovsky** [IIC2433/Syllabus-2020-2#37]
Hola, podemos asumir que los itemsets frecuentes tienen largo 2 o 3. Que no estoy seguro como se genera la regla de asociacion para un set de tamaño 4, y en el dataset que nos dieron no pasa. 
Gracias

**Comment by Hernan4444** [comment]
Hola, no puedes asumir eso. Lo esperado a evaluar es que sean capaces de construir un algoritmo genérico. Si el dataset no cuenta con ello, pueden generar un mini ejemplo (como los vistos en clases/ayudantias) y con un soporte bien pequeño para construir itemset frecuentes de mayor largo.

Saludos :v:

**Comment by danustilovsky** [comment]
Perfecto. Si tuviera un itemset frecuente como {a,b,c,d} las reglas de asociacion serian:

- a ->{b,c,d}
- b -> {a,c,d}
- ...
- {a,b} ->{c,d}
- ....
- {b,c,d} -> a

Esto esta bien? Gracias

**Comment by Hernan4444** [comment]
Exacto, luego tienes que calcular su confianza y lift para filtrar aquellas que no pasan el umbral indicado en la función `generate_association_rules`

Saludos :v:

**Comment by danustilovsky** [comment]
Buenisimo! Muchas gracias!
