### ISSUE TITLE
Duda 'criterios de calidad'

### ISSUE THREAD

**Issue by pazanelli** [IIC2433/Syllabus-2020-2#39]
Hola, en el enunciado, cuando dice 'Filtrar las reglas de asociación de acuerdo a dos criterios de calidad  definidos por mi'.. ¿se refiere al valor de lift y confidence que le pido? ¿o a qué otra clase de criterios?

**Comment by fguinez** [comment]
Puede que esto que respondieron en #20 te sirva:
> Hola,
> Asumo que te refieres a si solo deben usar lift, support y confianza o deben agregar otras métricas. Sobre esto, tienen total libertad de acción tanto para usar las 3 conocidas como para investigar y agregar otras.
> Saludos
> 
> _Originally posted by @Jiruiz2 in https://github.com/IIC2433/Syllabus-2020-2/issues/20#issuecomment-699557885_
