### ISSUE TITLE
Utilidad de lift

### ISSUE THREAD

**Issue by Zapararte** [IIC2433/Syllabus-2020-2#40]
¡Hola!
En otra issue se dijo que de acuerdo a los parámetros de la función `generate_association_rules(frequent_itemsets, confidence = 0, lift =0)` se espera que retornemos las reglas que cumplan ser mayor o iguales a estos umbrales. Lo que tiene sentido para el caso de la confianza, sin embargo para el lift valores "mejores" corresponden a aquellos que están lejos de lift = 1. Por esto pienso que es más lógico que el parámetro lift = X signifique quedarnos con las reglas cuyo lift es mayor a 1+X o menor a 1- X. 
¿Puedo asumir esto en mi tarea o me quedo simplemente con los valores de lift mayores al umbral?

Gracias de  antemano :)

**Comment by Hernan4444** [comment]
Hola,

Si puede asumir eso, pero que detallada esa información en tu código por si alguien lo tomó literal como >= a un umbral.

Saludos :v:

**Comment by Zapararte** [comment]
Perfecto, gracias!
