### ISSUE TITLE
Selección reglas al explicar las reglas obtenidas

### ISSUE THREAD

**Issue by fguinez** [IIC2433/Syllabus-2020-2#41]
Hola! En la parte 4 de la tarea se me ocurren varias interpretaciones y no sé cual está bien.

Las 4 reglas que se deben explicar pueden ser:
1. Las que yo quiera de entre las retornadas por `generate_association_rules`
2. Sólo puedo seleccionarlas de entre las 10 mejores reglas. De ser esta opción:
   a. Puedo elegir cualquiera de estas 10
   b. Deben ser las 4 mejores entre las 10 mejores

La inquietud me surge porque, a pesar de que una regla no sea tan buena, puede ser más enriquecedor explicar reglas de diferente calidad.

Saludos

**Comment by Hernan4444** [comment]
Hola,

Es la opción 1.

Saludos :v:
