### ISSUE TITLE
Usuarios sin transacciones post-preprocesamiento

### ISSUE THREAD

**Issue by lily416** [IIC2433/Syllabus-2020-2#42]
Me entró la duda qué hacer con los usuarios que después de pasar por `preprocess` se quedan sin transacciones (por ejemplo: alguien que su rating máximo fue un 3). ¿En el `ndarray` dejamos su posición con una lista vacía (para que así se cumpla la relación índice-id) o nos saltamos al usuario, ya que no aporta información para el modelo?
 
Gracias de antemano 🙇.

**Comment by fedetaladriz** [comment]
Hola @lily416 !
Efectivamente puede haber pasado, buena observación! Sin embargo, eso se manejó al momento de construir el dataset, por lo que no quedan usuarios con menos de cierta cantidad de ratings. Si quieres verlo tu misma, puedes ver que hay la misma cantidad de usuarios antes y después del preprocesamiento aplicando el método`unique()` a la columna `userId`. 
Saludos y suerte!
