### ISSUE TITLE
Grupos Proyecto

### ISSUE THREAD

**Issue by Hernan4444** [IIC2433/Syllabus-2020-2#43]
Esta issue es para que se puedan coordinar la búsqueda de integrante y para que los primeros **3 grupos** de 3 integrantes puedan avisar que no serán de 4 sino 3 personas. Todos los demás grupos deberán ser de 4 y contestar el siguiente formulario: https://forms.gle/den4v2wrVJ8642t19

Para los grupos que quieran ser de 3, deben escribir un comentario con el **nombre de sus integrantes** y su **usuario github** **en esta issue**, luego se les **confirmará la inscripción** por esta misma issue. Solo se aceptan comentarios nuevos, es decir, no se acepta comentar que son 1, 2 o 4 integrantes y luego editar para decir que son un grupo de a 3. En ese caso deberán hacer un nuevo comentario con los 3 integrantes. Una vez confirmado que son 3, no podrán cambia el grupo.

**Comment by cristian-vallejos** [comment]
Estoy en búsqueda de un grupo para desarrollar el proyecto final, por si a alguien le falta gente. Trato de ser lo más proactivo posible, aportando al trabajo en equipo.

**Comment by fnquinteros** [comment]
> Estoy en búsqueda de un grupo para desarrollar el proyecto final, por si a alguien le falta gente. Trato de ser lo más proactivo posible, aportando al trabajo en equipo.

aún te falta grupo? si es así, podríamos ser grupo de 3 con Nicolás Teare (usuario: nateare)

**Comment by cristian-vallejos** [comment]
> > Estoy en búsqueda de un grupo para desarrollar el proyecto final, por si a alguien le falta gente. Trato de ser lo más proactivo posible, aportando al trabajo en equipo.
> 
> aún te falta grupo? si es así, podríamos ser grupo de 3 con Nicolás Teare (usuario: nateare)

Sí. Apaño a ser los 3 (si es que aun hay cupo para grupos de 3). Nos inscribo en el formulario nomás ?

**Comment by fnquinteros** [comment]
> > > Estoy en búsqueda de un grupo para desarrollar el proyecto final, por si a alguien le falta gente. Trato de ser lo más proactivo posible, aportando al trabajo en equipo.
> > 
> > 
> > aún te falta grupo? si es así, podríamos ser grupo de 3 con Nicolás Teare (usuario: nateare)
> 
> Sí. Apaño a ser los 3 (si es que aun hay cupo para grupos de 3). Nos inscribo en el formulario nomás ?

ya porfa!

**Comment by fnquinteros** [comment]
en ese caso @Hernan4444, nuestro grupo sería:

Nicolás Teare: nateare
Cristián Vallejos: cristian-vallejos
Felipe Quinteros: fnquinteros

**Comment by Hernan4444** [comment]
@fnquinteros confirmó la inscripción del primer grupo de 3.

Nicolás Teare: nateare
Cristián Vallejos: cristian-vallejos
Felipe Quinteros: fnquinteros

Saludos :v:

**Comment by gustavo-toro** [comment]
Hola, nos falta uno en el grupo.
Mi correo gustavo.toro@uc.cl

**Comment by vtespinosa** [comment]
Hola! Con dos amigos estamos buscando a una persona más para el grupo. Cualquier cosa mi mail es vtespinosa@uc.cl.

**Comment by absoto4** [comment]
Hola @Hernan4444 , queremos ser grupo de 3:

Vicente Agüero: vicenteaguero
Antonia Soto: absoto4
Mathias Valdebenito: mathiasvaldebenito

**Comment by Hernan4444** [comment]
@absoto4 confirmó la inscripción del segundo grupo de 3.

Vicente Agüero: vicenteaguero
Antonia Soto: absoto4
Mathias Valdebenito: mathiasvaldebenito

Saludos ✌️

**Comment by mathiasvaldebenito** [comment]
no se puede pasar de un grupo de a 3 a uno de 4? acabamos de encontrar un nuevo integrante. Leí la issue, pero pregunto por si acaso :(

**Comment by mora4** [comment]
Hola @Hernan4444 , queremos ser un grupo de 3:

Vicente Espinoza: vtespinosa 
Jose Dominguez: josem7
Antonio Mora: mora4

Saludos!

**Comment by Hernan4444** [comment]
@mora4  confirmo el grupo de 3

Vicente Espinoza: vtespinosa
Jose Dominguez: josem7
Antonio Mora: mora4

@mathiasvaldebenito dado que no hay taaantos grupos que querían ser de 3 como pensabamos (y que terminaría siendo casi una pelea por los cupos de dichos grupos), se acepta que sean de 4. 

Dado lo anterior, solo hay 2 grupos de 3 por ahora. Faltaría 1.

Saludos :v:
