### ISSUE TITLE
T2 - Binning

### ISSUE THREAD

**Issue by VicenteVicente** [IIC2433/Syllabus-2020-2#44]
Solo para confirmar, ¿el Binning se aplica solamente a columnas numéricas, cierto?

Saludos :)

**Comment by Hernan4444** [comment]
Hola @VicenteVicente 

Así es

Saludos :v:

**Comment by cristian-vallejos** [comment]
Sería válido transformar columnas no numéricas para que se pueda aplicar algún método de binning sobre ellas?

**Comment by VicenteVicente** [comment]
Sobre el binning, creo que es un poco innecesario el pasar a 0s y 1s. ¿Se puede dividir de inmediato, saltándose este paso?

**Comment by Hernan4444** [comment]
Hola,

No se pueden saltar pasos.

Saludos :v:

**Comment by cristian-vallejos** [comment]
¿Sólo se hace binning sobre las columnas numéricas que vienen originalmente en el dataset? ¿O las categóricas (category, country, etc.) también deben transformarse?

**Comment by santilaguna** [comment]
@Hernan4444 @VicenteVicente  en donde aparece eso de data binning? en el enunciado no aparece que se separe en 1s y 0s, en verdad la pregunta es más que nada para entender mejor lo que hay que hacer

**Comment by Hernan4444** [comment]
Hola, 

Más que poner 1s y 0s, en el enunciado se indica que el método bining se encarga de categorizar una columna numérica (pagina 11 primeras líneas), es decir, transformar los números en categorías. Tu decides qué categorías usar, en el caso de @VicenteVicente, sus categorías son 0 y 1 y asumo que el nombre de esa columna es algo como "atributo >= X". Pero si isas otra nomenclatura para categorizar, estará bien. Por ejemplo, en vez de poner 0s y 1s, poner  "atributo >= x" y "atributo < x" y ahí tienes 2 strings que son tus categorías.

Saludos :v:

**Comment by bjbarias** [comment]
Hola! Me surge una duda con esta issue: cual sería el paso que se estaría saltando? Supongo que no hay que modificar el DataFrame verdad?

**Comment by Hernan4444** [comment]
Hola,

Por la pregunta de VicenteVicente, se entendía que él quería que bining no solo categorizara una columna, sino que directamente crear las divisiones/nodos pertinentes, pero ese paso no queremos que lo hagan en bining, sino que solo toma una columna numérica y la categoriza bajo cierto criterio. Luego, otro método  se encarga de crear los nodos necesarios según las categorías.

Saludos :v:

**Comment by bjbarias** [comment]
perfecto! Gracias!
