### ISSUE TITLE
T2 - Entropia

### ISSUE THREAD

**Issue by agustin-rios** [IIC2433/Syllabus-2020-2#45]
En el ejemplo que se hace sobre entropia nos muestran el funcionamiento de la función sobre solo un atributo, es correcto que si un nodo contiene más de un atributo  esto se sume tambien? o debe ser un calculo de entropia por atributo?

**Comment by Hernan4444** [comment]
Hola,

No te guíes solo del ejemplo del enunciado, este era más un mini recordatorio de cómo calcular entropía. **Recomiendo** revisar el ejemplo visto en clases y/o en la ayudantía. Con eso debería quedar clara tu consulta.

Saludos :v:

**Comment by Ajbarros1** [comment]
Hola! En clases vimos que la entropía se calculaba con logaritmo de base 2, pero en el enunciado de la tarea sale que se calcula con base 10. ¿Usamos la formula del enunciado o la de clases?

**Comment by Hernan4444** [comment]
Hola,

Se calcula con logaritmo en base 2, el enunciado tiene un error.

Saludos :v:
