### ISSUE TITLE
T2 - get_best_division()

### ISSUE THREAD

**Issue by VicenteVicente** [IIC2433/Syllabus-2020-2#46]
¿Por qué este método debe tan solo retornar _el nombre de la/s columna/s con las cuales hará la división el nodo_? ¿No sería mejor que realice la división de inmediato?

**Comment by sricke** [comment]
Hola @VicenteVicente,
El hecho que pedimos que retornen solo el nombre de la(s) columna(s) se debe para facilitar la corrección, pero si le das una vuelta al problema veras que si iteras sobre todas las columnas y vas guardando la separacion de datos resultante por cada una es muy probable que sobrecargues la RAM, por lo que ten cuidado. Por eso es mejor ir guardando solo el nombre de la mejor durante la iteración y queda a gusto de ustedes si prefieren hacer la separación según la(s) mejor(es) columna(s) justo antes o después de que retorne el método. 

Saludos!

**Comment by VicenteVicente** [comment]
Gracias!

**Comment by VicenteVicente** [comment]
Tengo una duda nuevamente sobre esto. El método `calculate_entropy` dice que "Calcula la entropía de los datos que tiene el nodo.", pero mencionaste que no era bueno poner los datos en el nodo mismo por la RAM, entonces, ¿no tendría más sentido tener este método en la clase `DecisionTree`, en vez de la clase `Node`?

**Comment by Hernan4444** [comment]
Hola, 

En el comentario anterior se refería a que si vas iterando por columna (para encontrar la mejor) y por cada intento que haces, guardas el nodo con su separación y datos correspondiente, podríamos tener problemas de RAM. Imagina que son 50 columnas, solo 1 ejecución de `get_best_division` hará que la ram se llene en un momento con 50 nodos diferentes y cada uno con los datos correspondientes a su división.

Lo esperado (y que es más eficiente en términos de memoria), es calcular **1 nodo posible**, obtener su ganancia y guardar en memoria solo el nombre de la columna que utilizó el nodo y la ganancia. De este modo, 1 ejecución de `get_best_division` solo ocupa la RAM correspondiente a calcular máximo 1 nodo (sin importar cuantas columnas son), y en memoria solo se guarda un string y un número, pero no cada nodo posible que experimentas.

Espero que haya quedado más claro a qué nos referimos con sobrecargar la RAM.
Saludos :v:

**Comment by VicenteVicente** [comment]
Entiendo! Gracias :)
