### ISSUE TITLE
t2 - columna id 

### ISSUE THREAD

**Issue by mgbriones** [IIC2433/Syllabus-2020-2#48]
hola, por comodidad se puede eliminar la columna ID ?

**Comment by Hernan4444** [comment]
Hola, 

Si puedes, pero en ese caso, hazlo de forma interna en el código (como indicando en el `__init__` del Arbol cuales columnas ignorar o utilizar) porque como no pueden subir el dataset, nosotros ocuparemos el original que si tiene esa columna.

Saludos :v:

**Comment by sebacarrasco** [comment]
Hola @Hernan4444, se puede hacer lo mismo con el nombre?

**Comment by Hernan4444** [comment]
Hola,

Si se puede, puesto que es una columna donde cada fila tiene un valor distinto. No aportará nada a la clasificación.

Saludos :v:
