### ISSUE TITLE
t2 . limpieza de los datos

### ISSUE THREAD

**Issue by mgbriones** [IIC2433/Syllabus-2020-2#49]
hola se debe hacer limpieza de todos lo datos entregados??
hay algunas filas columnas q tienen  `"0`  , estas filas deben ser eliminadas??

**Comment by Hernan4444** [comment]
Hola,

No es necesario hacer limpieza de datos, si utilizas pandas para abrir los archivos, ellos por defecto se encargaran de procesar bien las filas con esos "0 .En el peor de los casos que esas filas sigan generando problema (tal vez tu versión de Pandas es más vieja que la usada para crear los archivos), puedes filtrarlas; dada la cantidad de datos, eliminar esas filas no generará un problema. Aparte que el desempeño del árbol es solo una métrica que estamos usando como punto para comparar y comentar, nuestro énfasis no es que logren entrenar un árbol con un desempeño de 1 o lo mejor posible.

Saludos :v:
