### ISSUE TITLE
Duda FP Growth

### ISSUE THREAD

**Issue by inveterate-cladocerus** [IIC2433/Syllabus-2020-2#5]
Hola! Una duda con el algoritmo FP growth, una vez que tengo mi lista de itemsets frecuentes, por ejemplo si tengo un itemset {A, B, C}, debo probar todas las combinaciones de los subconjuntos del itemset para las reglas, que serían: {A} -> {B, C}, {B} -> {A, C}, {C} -> {A, B}, y lo mismo pero con la flechita en la otra dirección. Estoy bien?

**Comment by Jiruiz2** [comment]
Hola,

Estas en lo correcto, debes revisar todas las posibilidades.

Saludos.
