### ISSUE TITLE
T2 - [Retorno de métodos]

### ISSUE THREAD

**Issue by VicenteVicente** [IIC2433/Syllabus-2020-2#50]
Si un método debe retornar, por ejemplo X, ¿puedo hacer que retorne una una tupla de la forma (X, a, b, c, d...), es decir añadir más elementos al `return`, incluyendo el solicitado?

**Comment by Hernan4444** [comment]
Hola,

Es posible, solo recuerda detallarlo en la documentación/con comentarios de tu función para saber que serían esos A, b, c, d, etc.

Saludos :v:

**Comment by VicenteVicente** [comment]
buenísima, gracias :)
