### ISSUE TITLE
Cuestionario de Canvas Control 4

### ISSUE THREAD

**Issue by gicrot** [IIC2433/Syllabus-2020-2#52]
Hola! Estaba revisando y no se donde entregar el control 4, ya que no encuentro el cuestionario en Canvas correspondiente. No se si es mi pc o si aún no lo habilitan, pero eso.

Gracias de antemano.

**Comment by Hernan4444** [comment]
Hola,

No es tu pc, era que no estaba habilitado.

Saludos :v:
