### ISSUE TITLE
[Proyecto] Fuente de datos en formato encuesta

### ISSUE THREAD

**Issue by Oisangui** [IIC2433/Syllabus-2020-2#53]
Hola! Estamos pensando en hacer un sistema recomendador usando encuestas tipo google forms, el problema es que no tenemos manera de garantizar que hayan muchísimos datos disponibles para el análisis.

Hasta ahora tenemos 40 transacciones guardadas por la encuesta y nuestro con junto de items es de cardinalidad de entre 100 y 200. Pero nuestro proyecto tentativo es muy interesante porque tiene que ver con la universidad y la toma de cursos.

Es esto fatal para la propuesta? Cuántas transacciones necesitamos para que funcione si cada transacción tiene a lo más 4 items?

**Comment by Hernan4444** [comment]
Hola @Oisangui hablé con los demás ayudantes, recomiendo dejar esa propuesta como una tercera propuesta (y buscar 2 que si tengas datos). Puesto que tienes muy pocos datos y no sabemos si de aquí a la otra semana lograrían tener datos suficientes. En caso de no conseguir más, esto sería rechazado

Saludos :v:
