### ISSUE TITLE
T2 - Consulta Binning

### ISSUE THREAD

**Issue by cristian-vallejos** [IIC2433/Syllabus-2020-2#54]
Me surgieron un par de dudas con la implementación del método `binning`:

1. ¿Sólo se hace binning sobre las columnas numéricas que vienen originalmente en el dataset? ¿O las categóricas (main_category, country, etc) también deben transformarse para aplicarlo sobre ellas?

2. Si, por ejemplo, una columna numérica tiene una cantidad baja de valores únicos, ¿es necesario de todas maneras hacerle binning?

Quizás estoy mal entendiendo el concepto, pero creo que no está demás preguntarlo. ¡Gracias de antemano!

**Comment by IchottMano** [comment]
Hola! Para responder un poco tus dudas:

1. Efectivamente, nosotros hacemos binning **sólo** cuando tenemos un dato numérico que queremos convertir a categórico, ya que el DT trabaja con este tipo de datos. No es necesario y de hecho puede afectar negativamente a tus predicciones si intentas hacer de alguna manera binning de datos categóricos.

2. Para esto, hay que entender bien que significa **binning** . Cuando hablamos de binning nos referimos a un método que transforma datos numéricos a categóricos. Si tu tienes, por ejemplo, una columna donde los datos sólo son 0 o 1, es perfectamente correcto tomar esta columna como una categoría. El problema surge cuando tienes valores continuos, que difícilmente tienen pocos valores únicos, donde esperamos que usen las técnicas de binning pedidas. queda a tu criterio ver entonces que cantidad de valores únicos son suficientes para usar las estrategias que pedimos.

Saludos!

**Comment by cristian-vallejos** [comment]
Gracias, Rodrigo! Lo entendí perfectamente.

Una última consulta al respecto... ¿Podemos asumir que, por defecto, se sabrá qué columnas son numéricas y cuáles no? ¿O hay que implementar la lógica para que no se hagan pruebas con columnas no numéricas?

**Comment by sricke** [comment]
Hola Cristian,
Creo que tu pregunta tiene dos lados.

1. Para armar el árbol puedes guardar en una variable los nombres de las columnas categóricas y en otra las numéricas para saber como trabajar la posible separación de los datos según una columna candidata.

2. Para implementar el método predict la comparación del dato entregado con un nodo específico dependerá si es categórico (igual a) o numérico (menor o mayor) por lo que debes implementar alguna lógica para que haga la distinción.  

Saludos!

**Comment by cristian-vallejos** [comment]
Perfecto. Lo que más me confunde es que `binning` recibe el nombre de una columna y retorna un DataFrame, nparray o lo que uno quiera. ¿Esto es sólo para poder generar la comparación en el nodo, cierto? ¿No tiene nada que ver con modificar la columna en el mismo dataset?

Por último... ¿Cómo sabrá el método `binning` qué estrategia utilizar? ¿No hay drama si el nodo recibe el parámetro desde el árbol?

¡Gracias a ambos!

**Comment by sricke** [comment]
Hola Cristian,
Si solo para generar la comparación en el nodo y poder calcular la entropía resultante. Por esto mismo se pide retornar un nuevo DataFrame o nparray porque los valores originales de la columna no se deben modificar. Considera que luego los datos resultantos de un nodo hijo pueden ser separados nuevamente por la misma columna pero con nuevo valor de _binning_. 

Con respecto a lo segundo, se pueden hacer ese tipo de modificaciones en el código, es decir, los parámetros de las funciones y lo que retornan, según lo que estimen pertiente y que les facilite el trabajo, pero poniendo especial énfasis en documentar y explicar las razones de por qué se hizo así.

Saludos!

**Comment by pazanelli** [comment]
Hola, con respecto al binning en la parte de comparar estrategias. Una estrategia de binning sería por ejemplo 'cuartiles'? Y en ese caso, todo el árbol se debe construir usando siempre cuartiles para categorizar los datos en todas las columnas? O habría de definir estrategias distintas para cada columna no categórica según lo que haga más sentido a los datos?

**Comment by Hernan4444** [comment]
Hola,

Sería aplicar la **misma estrategia** (cuartiles por ejemplo) a todas las columnas no categóricos. No hay que definir diferentes estrategias por cada columna.

Saludos :v:

**Comment by JuaniAndres** [comment]
Hola una duda si se esta ocupando la estrategia de los cuartiles y dos de ellos tienen el mismo valor entonces agrupo los datos en 3 grupos o tengo que cumplir con mantener igual la cantidad de elementos en cada uno?

**Comment by Hernan4444** [comment]
Hola,

Puedes agrupar, sino puede que salgan errores como el siguiente. Si tienes 4 "1"s, ejemplo: [1,1,1,1]. Si divides por cuartil, quedaría que cada nodo tiene un "1". Luego, cuando te llega un dato con valor 1 ¿a qué nodo va?. Por lo tanto, se debería agrupar.

Saludos :v:

**Comment by tsgonzalez** [comment]
Hola! Si elijo hacer binning filtrando por mediana y por media aritmética, puedo utilizar la información de que el vector resultante va a ser 'binario'?? 

La pregunta va a que: supongamos elijo separar por mediana. Luego, el método binning me retorna un vector de 1's y 0's dependiendo si el valor de la columna elegida es menor o igual, o mayor a la mediana. Entonces, puede hacer algo tipo 
if vector[i] == 0: algo, elif vector[i]==1: otra cosa??

O debería tratarse exactamente de la misma manera que si dividiera , por ejemplo, en cuartiles (en cuyo caso no podría hacer if vector[i] == 0: algo, elif vector[i]==1, ya que tendría más de 2 clasificaciones posibles para cada valor en la columna). 

Al fin y al cabo, se supone que debo programar dependiendo de los métodos que yo elija para el binning así que me parece válido, pero es para estar seguro :)

**Comment by Hernan4444** [comment]
Hola @tsgonzalez 

Si, esperamos que la programación de tu árbol sea consistente con las 2 formas elegidas. Si elegiste 2 métodos que retorna siempre 0 o 1, entonces es adecuado asumir que tu binning siempre retornará un vector 'binario'.

Saludos :v:
