### ISSUE TITLE
T2 - metodo predict

### ISSUE THREAD

**Issue by mgbriones** [IIC2433/Syllabus-2020-2#55]
Hola tengo dudas sobre como funciona este metodo y como deberia funcionar, la idea es algo asi como iterar todos los datos sobre el arbol? algo asi?

**Comment by Hernan4444** [comment]
Hola,

Cuando entrenaste el árbol, cada nodo se encargó de dividir por alguna columa y cada hijo se obtuvo por un valor posible de la división. Por ejemplo, un nodo que divide por la columna "Categoría" y tiene dos hijos: uno que es "arte" y otro que es "ciencia".

Luego, en predict uno le pasa una conjunto de X  (muchas filas) y **para cada dato (x)** se le pregunta al nodo actual cual es la clase. Partiendo por el nodo padre:

1. Si el nodo actual que recibe la info es hoja, retorna solo la clase que corresponde
2. En caso de no ser hoja, revisa la columna por la cual hizo su división y le pasas el (x) al **nodo hijo que corresponda** para preguntarle la clase. Y se vuelve al paso 1.

Por ejemplo, usando el caso de la ayudantía (aceptar o rechazar una solicitud de curso). El árbol final era:

![image](https://user-images.githubusercontent.com/15641721/96356652-3abe8480-10c8-11eb-8298-331b46043a52.png)


Si te llega un dato que es:

![image](https://user-images.githubusercontent.com/15641721/96356669-4dd15480-10c8-11eb-8855-a21b8b127612.png)


Para determinar su clase: 

1. Le pasamos el dato al nodo padre. Como este no es hoja, revisa cuál fue la columna que usó para la división. En este caso es "Consecuencia" y le pasa el dato al hijo que corresponde a "Se atrasa la licenciatura" (el de más a la derecha).

2. El nuevo nodo (el de más a la derecha) vuelve a revisar si es nodo hoja. Como no lo es, revisa cuál fue la columna que usó para la división. En este caso es "otra_solicitud". Como el dato tiene en dicha columna un "Si". Le pasas el dato al hijo de la izquierda.

3. El nuevo nodo si es hoja, por lo tanto entrega una respuesta. En este caso es "No".


De este modo, el dato que llegó fue clasificado como "No", es decir, la solicitud no fue aceptada. Tu método predict debe hacer todo eso pero para una DataFrame de datos. Para cada uno, entregar una respuesta que en el caso de la tarea es "failed" o "successful".

Espero haber resulto tu duda.
Saludos :v:
