### ISSUE TITLE
T2 - atributos a utilizar

### ISSUE THREAD

**Issue by mpbascunan** [IIC2433/Syllabus-2020-2#56]
Hola, del dataset entregado sólo se utilizan los datos numéricos? ignoramos los atributos de categorías y pais?

**Comment by sricke** [comment]
Hola! 

La idea es ocupar todas las columnas asique efectivamente debe existir una lógica que diferencie entre columnas categóricas y numéricas para armar el árbol y luego predecir acordemente.

Considera que el _binning_ es una forma de categorizar columnas numericas (valores continuos) para luego hacer comparaciones binarias (mayor o menor) o por segmentos (en el enunciado se menciona deciles o quartiles). 

Saludos!

**Comment by mpbascunan** [comment]
Graciaas!

**Comment by sricke** [comment]
Hola!

Solo quería complementar mi respuesta por una nueva duda que surgio en otra issue. Cuando digo que debe exisitir una lógica que diferencie entre columnas categóricas y numéricas para armar el árbol, esta lógica debe ser genérica y por ende debe ser el mismo algoritmo que detecte que columnas son catégoricas o númericas y estos valores no se pueden hardcodear. Sí se puede (y se recomienda) que reciba como parámetro los nombres de todas las columnas a utilizar, para evitar usar columnas que no sirven en este caso como por ejemplo _name_. 

La idea de esto es que el algoritmo sea lo más genérico posible y que pueda aplicarse en cualquier dataset.

**Comment by mpbascunan** [comment]
osea las columnas que podemos ignorar en este caso son id y name?

**Comment by Hernan4444** [comment]
@mpbascunan  así es, porque cada proyecto tendrá un ID y nombre distinto, así que no sirve como categoría para clasificar.

Saludos :v:

**Comment by fnquinteros** [comment]
Entonces, no es correcto asumir que al árbol se le pasará un dataset en que todas las columnas sirvan para clasificar?

**Comment by Hernan4444** [comment]
Hola,

En caso de hacer ese supuesto, entonces antes de llamar al `fit`, deberías tener alguna línea que se encarga de seleccionar las columnas que quieres usar o de filtrar aquellas que quieres ignorar. Lo que **no queremos** es que vayan a hardcodear su clase DecisionTree con algo específico de este dataset.

Lo siguiente es lo que queremos evitar

```python
def train(self, X, Y):
    X.remove("name")
    X.remove("ID")
```

porque en caso de usar otro dataset, se va a caer porque "name" y "ID" no existen. 

Saludos :v:
