### ISSUE TITLE
T2 - Argumentos cut_type y strategy

### ISSUE THREAD

**Issue by fguinez** [IIC2433/Syllabus-2020-2#57]
En el [google colab](https://colab.research.google.com/drive/18u09fGKWmKKPoDSkPSYOfAKFyQf-Dhrl) linkeado en el enunciado, el método `__init__` de la clase `DecisionTree` tiene entre sus argumentos `cut_type` y `strategy`.

¿Cuál es la diferencia entre estos argumentos? Dado que del enunciado me queda la noción de que ambos se refieren a la estrategia de separación de los datos (tradicional o transversal).

Saludos!😄

**Comment by Hernan4444** [comment]
Hola, 

Uno es tipo de corte: tradicional o transversal (cut_type) y el otro es la estrategia de bining (strategy)

Saludos :v:

**Comment by fguinez** [comment]
Aah perfecto! Muchas gracias👌
