### ISSUE TITLE
Gain = 0

### ISSUE THREAD

**Issue by sebacarrasco** [IIC2433/Syllabus-2020-2#59]
Hola una duda, cuando solo me queda una columna por la cuál hacer divisiones pero el gain es cero, se debe hacer esa división o no?
Entiendo que no aportará a la toma de decisiones pero lo pregunto porque afecta la altura del árbol y afectaría la visualización.

Aprovecho de hacer otra duda que me surgió, si yo quiero predecir un dato, llego a un nodo (no hoja), al comparar el atributo del dato por el que se hizo división en ese nodo con los valores de los nodos hijos para saber a qué nodo pasar y en ningún caso son iguales, entonces se debe hacer la predicción con el nodo en el que estoy y no seguir?

**Comment by Hernan4444** [comment]
Hola, dado que es un caso particular (una división con ganancia 0), lo dejamos a tu criterio, pero deja detallado en tu tarea (en una casilla de texto) dicho criterio.

Sobre la segunda duda, ante esos casos generalmente un árbol se cae. Aquí dejamos a tu criterio qué acción tomar. Una opción  sería que el árbol solo retorna la clase de aquellos datos que puede procesar y de los que no (como el caso que indicas), los ignora. Otra opción es que aquellos que no puede clasificar siempre retorna una misma clase (Aceptado o rechazado).  Solo recuerda especificarlo en tu tarea la decisión que tomes.

Saludos :v:

**Comment by Hernan4444** [comment]
Hola,

Para complementar, ¿cómo te da eso de ganancia 0? Porque eso solo sería factible con un dataset 100% categórico, pero si hay una o más columna numérica, esas se pueden volver a utilizar para generar divisiones con ganancia distinta a 0

Por ejemplo, dividir por la mediana y luego, los datos que son menores a la mediana, dividir nuevamente por la mediana. Con esto quiero hacer hincapié que es difícil que te de dicho caso para esta tarea donde solo te quede 1 columna y haya ganancia 0 con dicha columna dada la presencia de columnas numéricas. (Ver issue #60).

Saludos :v:

**Comment by sebacarrasco** [comment]
Hola Hernan! Creo que tienes toda la razón jajaj esa pregunta la hice antes de revisar esa issue, entonces al hacer separación por un dato categórico no volvía a tomar en cuenta esa columna. Ahora voy a arreglar eso y probablemente ya no me pase eso del gain igual cero.
Mucha gracias!

**Comment by sebacarrasco** [comment]
Hola @Hernan4444 , me surgió una duda con lo que dijiste:

> Aquí dejamos a tu criterio qué acción tomar. Una opción sería que el árbol solo retorna la clase de aquellos datos que puede procesar y de los que no (como el caso que indicas), los ignora. Otra opción es que aquellos que no puede clasificar siempre retorna una misma clase (Aceptado o rechazado). Solo recuerda especificarlo en tu tarea la decisión que tomes.

En el caso de querer retornar siempre una misma clase, se puede hardcodear successful/failed?
