### ISSUE TITLE
T2 - Dividir dos veces con el mismo atributo

### ISSUE THREAD

**Issue by fguinez** [IIC2433/Syllabus-2020-2#60]
Hola!

¿Podemos asumir que en un camino del arbol se usará máximo 1 vez cada atributo como divisor?

Para los atributos categóricos esto es trivial, pero no estoy seguro con los atributos numéricos. Por ejemplo:
Si tenemos un atributo con valores del 1 al 100 y mediana 50, una opción es hacer bining por la mediana. Esto nos dejaría todos los valores entre 0 y 50 en uno de los nodos hijo, ¿es necesario considerar un nuevo bining de este subconjunto como candidado a mejor divisor?

**Comment by sricke** [comment]
Hola!,

Efectivamente se puede repetir un atributo numérico en el camino de un árbol por lo que habría que considerar en nodos sucesivos que se haga bining a partir de la misma columna. 

Saludos!

**Comment by inveterate-cladocerus** [comment]
¿Se puede concluir de lo anterior que las columnas originales con valores numéricos siempre se van a tener que entregar a los nodos hijos, ya que el binning va ir variando?

**Comment by Hernan4444** [comment]
Hola,

Depende mucho de la implementación.  Por lo tanto, más que decir

> "siempre se van a tener que entregar a los nodos hijos"

Lo correcto sería decir que
>  "siempre un nodo hijo deberá tener acceso de alguna forma a los valores de las columnas numéricas. No se pueden descartar como es en el caso de las columnas categóricas donde todos los datos de ese nodo tendrán la misma categoría".

Saludos :v:

ps: Cuando acabe la tarea, podría explicar porqué depende de la implementación.

**Comment by cristian-vallejos** [comment]
En ese caso, entonces, ¿la columna numérica se dividiría en muchas oportunidades y, por lo mismo, el árbol tendría una profundidad considerable o no?

Pregunto lo anterior porque, en un principio, había implementado una especie de restricción por nodo para que los nodos descendientes no pudieran volver a dividirse por atributos que ya habían dividido a sus ancestros, pero eso me generó predicciones muy malas.

**Comment by Hernan4444** [comment]
Hola,

Si, se puede dividir en muchas oportunidades. (Tal como sale en la figura 5 del enunciado que se ocupa más de una vez glucosa y BMI para formar divisiones).

Sobre el desempeño del árbol, no es un foco lograr entrenar un árbol con buen desempeño, solo que ocupen esa métrica como forma de comparación y cuando experimenten, **entre los resultados que lograron de sus experimentos** tomar el mejor, pero si ese mejor tiene un desempeño de 0.1, será nomás, luego pueden comentar que los resultados son malisimos con cualquier configuración (por ejemplo).

Saludos :v:
