### ISSUE TITLE
Hardcodeo lml

### ISSUE THREAD

**Issue by inveterate-cladocerus** [IIC2433/Syllabus-2020-2#61]
Hola, vengo a hacer una pregunta vergonzosa y polémica, ¿se pueden hardcodear los nombres de las columnas? No me juzguen uwu.

**Comment by Hernan4444** [comment]
Hola,

No se puede hardcodear. A lo más podrías hacer que el `fit `o el `__init__` reciba un parámetros de "columnas  a ocupar" o "columnas a ignorar" donde le dices que columnas del Dataframe puede usar o ignorar y en caso de ser None, usa todas. De este modo, si queremos usar otro dataset, solo tenemos que cambiar ese parámetro. De este modo árbol mantiene su capacidad de ser genérico y poder aplicarlo a cualquier dataset.

Saludos :v:

**Comment by sricke** [comment]
Hola!

Complementando lo que djo Hernán, la idea es que tu algoritmo reciba las columnas a ocupar ya que existen algunas columnas como _Name_ que en este caso no aportan nada a este algoritmo. Pero, no puede recibir las columnas categóricas y numéricas como parámetros distintos, la idea es que tu función detecte cuales columnas son categóricas o numéricas, logrando así que el algoritmo sea lo más genérico posible

Saludos!

**Comment by prochotito-rises** [comment]
Hola @sricke, me confundió un poco lo que dijiste, porque si le entregara una variable columnas a ocupar a mi algoritmo que, por ejemplo, no considerara ni la columna ID ni Name, porque no aportan a la predicción, ¿no tendría que hardcodear?  
Saludos!

**Comment by sebacarrasco** [comment]
Hola y los valores de la columna a predecir? ("successful" y "failed"))?

**Comment by Hernan4444** [comment]
Hola, tampoco se puede hardcodear eso. En el código base (y enunciado) se especifica que el método `train` recibe  X, Y, es decir ya está separado la parte de datos para entrenar y la columna a predecir. El árbol debe ser capaz de detectar cuales valores son los posibles de dicha columna.

Saludos :v:
