### ISSUE TITLE
T2 - Valores en test y no en train

### ISSUE THREAD

**Issue by fguinez** [IIC2433/Syllabus-2020-2#62]
Hola!

Me encontré con un valor en el dataset de test que no está en train. En específico, en `country` aparece el valor `'N,0"'`, buscando en Kaggle encontré [esta aclaración](https://www.kaggle.com/kemical/kickstarter-projects/discussion/177920) donde dicen que es solo un error.

De esta situación me salen 2 dudas:
1. ¿Podemos simplemente ignorar las filas con `'N,0"'`?
2. ¿Debemos ponernos en el supuesto de que habrán otros posibles valores no presentes en train?, de ser así ¿cómo manejamos estos casos?

**Un ejemplo ilustrativo de la segunda duda:** Si con train generé un arbol con esta división:
```
División por país
|-- USA
|-- Chile
`-- Argentina
```
¿Qué debería hacer si en test tengo un item con país `Wakanda`?

**Comment by Hernan4444** [comment]
Hola,

Aquí dejamos a tu criterio qué acción tomar (en ambos casos). Una opción  sería que el árbol solo retorna la clase de aquellos datos que puede procesar y de los que no (como el caso que indicas), los ignora/filtra. Otra opción es que aquellos que no puede clasificar siempre retorna una misma clase (Aceptado o rechazado).  Solo recuerda especificarlo en tu tarea la decisión que tomes.

Saludos :v:
