### ISSUE TITLE
Tipo de dato del atributo a predecir

### ISSUE THREAD

**Issue by inveterate-cladocerus** [IIC2433/Syllabus-2020-2#63]
Hola, ¿podemos asumir que el atributo a predecir siempre será categórico? ¿O pueden haber casos en que se tenga que hacer un binning inicial a esta columna?
Saludos.

**Comment by Hernan4444** [comment]
Hola, 

Si, pueden asumir eso.  Porque en caso de predecir un valor numérico, la forma de trabajar es distinta dado que en ese caso sería un Árbol de regresión.


Saludos :v:
