### ISSUE TITLE
Cortes transversales

### ISSUE THREAD

**Issue by cristian-vallejos** [IIC2433/Syllabus-2020-2#64]
Para el árbol con cortes transversales, ¿se debe escoger las dos columnas con más ganancia y separar ambas dejando, por ejemplo, siempre 4 nodos hijos? Pongo un ejemplo para que se entienda mejor mi pregunta (`X = criterio tal que los valores de la columna sean iguales a la moda`):

- **Hijo 1**: Ambas columnas coinciden con el criterio X.
- **Hijo 2**: Sólo la columna 'A' coincide con el criterio X.
- **Hijo 3**: Sólo la columna 'B' coincide con el criterio X.
- **Hijo 4**: Ninguna de las columnas coincide con el criterio X.

 ¿O la cantidad de hijos dependerá de la cantidad posible de combinaciones entre los valores de ambas columnas?

¡Muchas gracias!

**Comment by Hernan4444** [comment]
Hola,

Será la cantidad de combinaciones posibles. En este caso, si X es el criterio indicado, serán 4 hijos, puesto tendrás la combinación:

* Hijo 1: True - True
* Hijo 2: True - False
* Hijo 3: False - True
* Hijo 4: False - False

Pero si por ejemplo, tuvieras 2 columnas cuyos valores son:
* Columna A: "gato", "perro", "pollo".
* Columna B: "rojo", "verde", "azul".

Tus hijos serían:   "gato-rojo", "gato-verde", "gato-azul", "perro-rojo", "perro-verde", "perro-azul", "pollo-rojo", "pollo-verde", "pollo-azul".

Espero haber resulto tu duda.
Saludos :v:

**Comment by cristian-vallejos** [comment]
Ufff... En ese caso, para el ejemplo de la tarea, si ramifico por una columna categórica, entonces tendría una cantidad significativa de hijos por nivel, ¿cierto? ¿O, si aplico un criterio determinado para la definición de los hijos, basta y sobra?

Al final, lo que me confunde es que no sé si puedo o no aplicar un criterio propio para determinar cómo se construirán los hijos.

**Comment by Hernan4444** [comment]
Hola,

Precisamente, tendrás una cantidad significativa de hijos por nivel, pero eso reduce la profundidad de árbol. 

Tienen que cumplir lo que pide el enunciado de **hacer todas las combinaciones de valores**. Lo que podemos dejar a tu criterio es **qué hacer con los hijos que no reciban ningún solo dato**. Por ejemplo, si de los 9 hijos producto de la combinación de gatos,perros, pollo, y los colores, la combinación "perro-azul" te entrega un dataset vacío, podemos dejar a tu criterio si dicho nodo es creado o no, pero esperamos ver que en un árbol transversal, se vean la combinación de los valores de 2 columnas.

Saludos :v:

**Comment by cristian-vallejos** [comment]
Vale, vale. Lo entendí perfecto.

Te pasaste, Hernán. ¡Muchas gracias!

**Comment by cristian-vallejos** [comment]
Hola,

¿Es posible tener acceso a un ejemplo de cómo se obtendría el Information Gain para una separación generada por las combinaciones entre dos pares de columnas?

**Comment by cristian-vallejos** [comment]
Chiquillos,

Disculpen que insista con esta duda, pero de verdad no logro visualizar cómo podría adaptar el cálculo del Information Gain para un árbol tradicional en uno de cortes transversales.

Muchas gracias de antemano.

**Comment by Hernan4444** [comment]
Estimado,

Considera cómo se calculó la ganancia de un posible división en la ayudantía. Una corte transversal solo cambia como se forma el nodo, pero la entropía y la ganancia se calcula en función de los datos que contiene los nodos que se pueden formar. 

Saludos  :v:

**Comment by cristian-vallejos** [comment]
Vale, perfecto. Mala mía entonces por no haberla visto.

¡Gracias, Hernán!

**Comment by cristian-vallejos** [comment]
Hernán,

Una última duda (y perdona que insista tanto en esto, pero necesito estar 100% seguro). En el enunciado, el apartado ***3.2 Tipo de corte*** especifica que serán 2 nodos hijos en un árbol tradicional y 4 en el árbol transversal, lo cual se contradice con lo dicho anteriormente en el apartado ***2.1 Cortes transversales*** donde se habla de todos los posibles valores. ¿A qué parte le hacemos caso?

Gracias de antemano.

**Comment by Hernan4444** [comment]
Hola,

Ambas partes están ciertas, esa parte que dice "2 nodos hijos y 4 en el árbol transversal" se está haciendo referencia al ejemplo anterior (figura 2 y figura 3) para recalcar que serán árboles sí o sí distintos.

Saludos :v:
