### ISSUE TITLE
T2 Nodo con entropía 1

### ISSUE THREAD

**Issue by JuaniAndres** [IIC2433/Syllabus-2020-2#65]
Hola, una duda si después de realizar una división termino con un nodo con entropía 0 y otro con entropía 1 asumo que en ambos no se continúan las divisiones? (el de entropía 1 tiene dos datos que varían solamente en sus id, nombre y state). En el caso en que llegue a ese nodo con entropía 1 durante una predicción la clase retornada queda a mi criterio?
Gracias de antemano

**Comment by Hernan4444** [comment]
Hola,

Hola, solo con entropía 0 podría ser una forma de no continuar porque no asegura más ganancia, pero entropía 1 todavía puede ser posible reducir la ganancia. No obstante, para el caso que describes donde solo te queda el ID y nombre, ya se puede decir que no hay más atributos para generar divisiones.

En relación a la segunda pregunta, queda a tu criterio, pero recomiendo revisar la ayudantía de árboles de decisión que ahí se tocó un poco de lo que estás preguntando.

Saludos :v:

**Comment by JuaniAndres** [comment]
Perfecto, muchas gracias hernan
