### ISSUE TITLE
normalizacion

### ISSUE THREAD

**Issue by mgbriones** [IIC2433/Syllabus-2020-2#67]
una duda en la ayudantia de astrid, decía que es necesario normalizar los datos para la tarea.. ha q se refiere esto? pensé que el árbol de decicion se encargaba de decidir respectos a los datos que se le entregaba, no veo la necesidad de hacer una normalización.

**Comment by Hernan4444** [comment]
Hola,

En este caso no es estrictamente necesario normalizar, solo que es recomendable tener en cuenta ese paso porque hay muchos otros modelos que si se verán beneficiados. Dado esto, si normalizaste en esta tarea, bien; si no lo haces, no hay drama, no se aplicará descuento.

Saludos :v:

**Comment by mgbriones** [comment]
gracias!
