### ISSUE TITLE
Visualización árbol

### ISSUE THREAD

**Issue by pazanelli** [IIC2433/Syllabus-2020-2#68]
Hola, 
llevo un rato intentado implementar la visualización del arbol, pero no encuentro información sobre cómo hacerlo ni en Matplotlib ni en Networkz que eran las librerías que tenía instaladas. Instalé Graphviz pero solo encuentro ejemplos que lo usan desde un árbol creado con sklearn, que lo exporta a graphviz directamente. 
Hay algún consejo/ documentación/ o algo recomendado? LLevo varios intentos y mucha búsqueda :(

**Comment by cristian-vallejos** [comment]
Paloma,

Yo encontré esta documentación para hacerlo [mediante nodos y arcos](https://graphviz.readthedocs.io/en/stable/examples.html). Espero que te sirva! 😄
