### ISSUE TITLE
Duda Tarea, Actividad 2

### ISSUE THREAD

**Issue by Natichubretovic** [IIC2433/Syllabus-2020-2#7]
Hola! En la Tarea, el método mine_tree de la clase fptree no debería recibir también min_support para generar itemsets frecuentes?

**Comment by Jiruiz2** [comment]
Hola,

Estas en lo correcto, actualizaremos el enunciado en breve. 

Muchas gracias

**Comment by Natichubretovic** [comment]
Gracias!
