### ISSUE TITLE
Tamaño de los árboles

### ISSUE THREAD

**Issue by cristian-vallejos** [IIC2433/Syllabus-2020-2#70]
¿Hay algún problema si los árboles se salen del margen del Jupyter? Lo que pasa es que si los adapto al ancho de la pantalla, no se ve absolutamente nada del contenido de los nodos (adjunto evidencia).

![image](https://user-images.githubusercontent.com/18368301/97496771-386ded00-1948-11eb-8a1a-5f06922cd8b5.png)

Sin embargo, si lo hago admitiendo libertad de crecimiento de la imagen, habría que recorrerla mediante scroll, pero se verían los detalles de la siguiente manera (adjunto otro árbol):

![image](https://user-images.githubusercontent.com/18368301/97496961-8551c380-1948-11eb-8749-9036ae65defb.png)

**Comment by Hernan4444** [comment]
Hola, 

No hay problema con hacer scroll.

Saludos :v:
