### ISSUE TITLE
Condicion de termino para Estrategias

### ISSUE THREAD

**Issue by danustilovsky** [IIC2433/Syllabus-2020-2#71]
Hola!  para la parte de estrategias podemos usar hiperparametros?? Dado que me pasa que se queda devidiendo infinitamente las columnas numericas y el arbol no se termina de generar. O existe alguna forma de evitar que esto pase? Gracias

**Comment by Hernan4444** [comment]
Hola, 

No hay problema con hacer eso mientras ambos dataset se le entregue el mismo hiper parámetro. De este modo, los árboles solo se van a diferenciar en la estrategia elegida.

Saludos :v:
