### ISSUE TITLE
[T2] Qué hay que visualizar exactamente? 

### ISSUE THREAD

**Issue by tsgonzalez** [IIC2433/Syllabus-2020-2#72]
Cuando dicen 'En esta visualización se tiene que ver como mínimo: (1) el atributo por el cual se está haciendo la división y (2) Que valor/es se hace en la división' , a qué se refiere el (2)? 

Gracias desde ya.

**Comment by Hernan4444** [comment]
Hola,

Por ejemplo, si divides por la mediana, ¿cual es la mediana 20, 30, 50?. En caso que la mediana sea 50, ¿cual nodo es < 50 y cual es >= 50?, Ahora si existiera una columna que es País, un nodo divide por el atributo país, pero ¿a qué país corresponde cada hijo? a eso nos referimos con (2).

Saludos :v:
