### ISSUE TITLE
Métricas de evaluación de desempeño

### ISSUE THREAD

**Issue by cristian-vallejos** [IIC2433/Syllabus-2020-2#73]
¿Se puede utilizar sklearn para obtener el accuracy de los modelos? ¿O necesariamente debe iterarse sobre `Y_test` para obtener el desempeño de las predicciones?

**Comment by Hernan4444** [comment]
Hola,

Como indica el enunciado, no se puede usar ninguna librería aparte de las mencionadas en el enunciado. Solo en la parte de visualización damos más libertad. Dado esto, no se puede ocuapr `sklearn`.

Saludos :v:

**Comment by cristian-vallejos** [comment]
Perfecto, master. ¡Muchas gracias!
