### ISSUE TITLE
Nodos sin datos

### ISSUE THREAD

**Issue by danustilovsky** [IIC2433/Syllabus-2020-2#74]
Hola, estaba probando mi arbol y me di cuenta que hay algunas divisiones en las cuales quedan nodos sin datos. Que debe responder ese nodo en ese caso? o hay alguna manera de evitar que esto pase?

Muchas gracias!

**Comment by Hernan4444** [comment]
Hola,

En ese caso, ese nodo no debería existir, no aporta nada al árbol. Incluso, no sería posible calcular la entropía de dicho nodo porque la entropía utiliza el total de datos de dicho nodo como denominador y dividir por 0 daría error.

Saludos :v:

**Comment by danustilovsky** [comment]
Toda la razon! gracias!
