### ISSUE TITLE
t2 - eliminar columnas ID y name

### ISSUE THREAD

**Issue by mgbriones** [IIC2433/Syllabus-2020-2#75]
Hola si quisiera eliminar estas dos columnas es obligatorio hacerlo en el __innit__ ? en mi codifgo se eliminan en otro metodo,  si lo hago en __innit__ me surgen problemas de ram.

**Comment by Hernan4444** [comment]
Hola,

Si las eliminas antes, no hay drama. Nos interesa que tu código (clase DecisionTree o Node) no tenga hardcodeado el eliminar esas columnas como mostré en la issue #56 

Saludos :v:
