### ISSUE TITLE
T2 - Fit

### ISSUE THREAD

**Issue by IvaniaArias** [IIC2433/Syllabus-2020-2#76]
Holaa!
No entiendo que es especificamente lo que debe hacer el método fit :(
Creo que aun no entiendo bien que es 'entrenar el arbol' jaja gracias de antemano!

**Comment by Hernan4444** [comment]
Hola,

Con 'entrenar el árbol' nos referimos al proceso que hicimos en la ayudantía de construir el árbol, Esto implica partir primero con 1 nodo, luego identificar la división que mayor ganancia entrega y construir nodos en función de dicha división. Luego hacer eso recursivamente para cada nodo hasta ya no poder seguir dividiendo los datos.

Saludos :v:

**Comment by IvaniaArias** [comment]
Perfectooo, muchas graciaas!
