### ISSUE TITLE
T2 Presentación y uso de dataset. 

### ISSUE THREAD

**Issue by hsazos** [IIC2433/Syllabus-2020-2#77]
Hola!

Para esta parte del puntaje, ¿Afectará si mi código esta en spanglish? Todas mis variables tienen nombres descriptivos, pero hay algunas variables en español, y otras en ingles.

Saludos

**Comment by hsazos** [comment]
Y otra duda, es posible que mi Entropia me de mas de 1? Cuando la calculo para "goals" y "duration_days" en el dataframe de train_small me da sobre 1 :(.

**Comment by Hernan4444** [comment]
Hola, 

No hay problema que sea spanglish. Por otro lado, no es imposible que una entropía de mayor a 1.

Saludos :v:
