### ISSUE TITLE
t2-formato de entrega

### ISSUE THREAD

**Issue by mgbriones** [IIC2433/Syllabus-2020-2#78]
los siguiente metodos pueden tener argumentos?
-calculate_entropy
-get_best_division
-bining
-check_deep
-check_min_data

**Comment by Hernan4444** [comment]
Hola, 

Citando lo que se dijo en la issue #54 

> se pueden hacer ese tipo de modificaciones en el código, es decir, los parámetros de las funciones y lo que retornan, según lo que estimen pertiente y que les facilite el trabajo, pero poniendo especial énfasis en documentar y explicar las razones de por qué se hizo así.

Solo tengan en cuenta de respetar el formato de lo pedido que haga cada función.

Saludos :v:
