### ISSUE TITLE
Dudas Control 05

### ISSUE THREAD

**Issue by Hernan4444** [IIC2433/Syllabus-2020-2#85]
# Control 05: Dudas Frecuentes

## General

1. Lo entregado debe ser un PDF. Puede ser hecho a mano, foto, scanner, pero **debe** ser PDF.

2. ¿Se puede mezclar partes hechas a mano y otras en PC, Escaneando las partes a mano? Si, mientras al final entregas un PDF, se entienda todo y sea algo que hiciste tu.

## Pregunta árboles de decisión

1. ¿Se aplica código de la tarea?: No, escribir paso a paso como se vió en ayudantía y en clases.

2. ¿Con porcentaje de certeza se refiere a la incertidumbre?  En las hojas es posible identificar con cuanto % el algoritmo cree que el resultado es de cierta clase. Ese % es el pedido.

3. ¿Se asume árbol tradicional? Si, el común. No el transversal que vimos en la tarea.

4.  ¿Qué pasa en caso de empate? (cual es el criterio?). Deben definir un criterio **determinista**.

## Pregunta Random Forest

1. ¿Las 2 preguntas de random forest son aparte?  Si, la primera no depende de la segunda.

2. En la pregunta de reducir las dimensiones, da lo mismo si es el random forest es un regresor o un clasificador, no influye en la pregunta.

3. En la pregunta de reducir las dimensiones, imaginen que tienes el dataset y únicamente el Random Forest. Deben responder a ¿cómo usar el algoritmo para permitir que el dataset de N dimensiones ahora tenga M dimensiones? 

4. ¿En la parte 1, en la explicación de random forest debemos incluir la explicación del algoritmo? No, se asume que ya lo conocen, solo indicar qué parte de él modificarían para que haga una regresión en vez de una clasificación.

## Pregunta Naïve Bayes

1. ¿La probabilidad la podemos calcular visualmente si explicamos cómo se hace o tiene que ser con bayes?  Deben usar Naïve Bayes, no explicar visualmente.

**Comment by hsazos** [comment]
Es posible que el árbol en la 1 tenga muy poca profundidad?

**Comment by rociomartineza** [comment]
Se sube en el buzon de canvas? Creo que no hay ninguno creado

**Comment by tsgonzalez** [comment]
En la 1 de arboles de decision, puedo utilizar un poco de lógica que sea programable para saltarme pasos? 
O sea, si me doy cuenta de algo que me ahorra pasos y en la práctica podría llegar y hacer 
'if esto.. saltate pasos' 
entonces puedo hacer lo mismo en mi respuesta? o es necesario hacer todos los pasos, aunque ya sé que no me sirve de nada seguir haciendo algunos.

**Comment by Hernan4444** [comment]
Hola,

@hsazos no podemos decir eso, si el armado fue correcto, entonces no se deben preocupar de la profundidad.
@rociomartineza acabo de crear el buzón.
@tsgonzalez no pueden saltarse pasos.

Saludos :v:

**Comment by alericoj10** [comment]
Hola, creo que el buzon de canvas no tiene la opcion para subir archivo

**Comment by Hernan4444** [comment]
@alericoj10 

Listo, ahora si pueden subir el archivo.

Saludos :v:

**Comment by raespinoza4** [comment]
En la pregunta 3 de Naive Bayes con la frase "Basado en los datos previos" se refiere a utilizar las probabilidades calculadas en 1 y 2 o al dataset de la pregunta ?
