### ISSUE TITLE
T3 | Tipo de dato "weight"

### ISSUE THREAD

**Issue by felipearellanom** [IIC2433/Syllabus-2020-2#86]
Estaba viendo la base de datos y resulta que la columna "Weight" no es numérica si no que es nominal agrupada en intervalos de 25 libras. Esto es un error de enunciado o debería tratarlos todos como Nan?

**Comment by AstridESMJ** [comment]
Hola,
Debes revisar bien cada atributo y decidir qué hacer con cada uno, en la ayudantía hablamos al respecto para que lo revises.
Saludos,

Astrid
