### ISSUE TITLE
Archivo repetido en Syllabus

### ISSUE THREAD

**Issue by fguinez** [IIC2433/Syllabus-2020-2#87]
Hola!

Hace unas semanas que tengo problemas para usar mi versión local del Syllabus, porque el archivo `Ayudantia_1_programación_vectorial.ipynb` en el directorio [`Ayudantías/Ayudantía 1`](https://github.com/IIC2433/Syllabus-2020-2/tree/master/Ayudant%C3%ADas/Ayudant%C3%ADa%201) está repetido con el mismo nombre.

![Captura de pantalla del directorio](https://user-images.githubusercontent.com/26127246/99884200-1136d280-2c0b-11eb-8632-d1cca14bc899.png)

Agradecería si lo pueden solucionar😄

**Comment by Hernan4444** [comment]
Hola, 

Se ha eliminado el archivo. ¿Puedes intentar nuevamente para contarnos si ahora te funcionó?

Saludos :v:

**Comment by fguinez** [comment]
Ahora funciona sin problemas, gracias!
