### ISSUE TITLE
Duda preprocesamiento

### ISSUE THREAD

**Issue by inveterate-cladocerus** [IIC2433/Syllabus-2020-2#88]
Hola, para la parte en la que debo decidir si borrar algunas columnas o no, ¿mi código debe llegar automáticamente a este resultado, o puedo hacer el análisis aparte y en el código solo transmitir el resultado de cuáles columnas borrar?
Saludos

**Comment by AstridESMJ** [comment]
Hola!
Puedes hacer el análisis aparte y en el código solo transmitir el resultado de cuáles columnas borrar, no hay problema con eso.

Saludos,

Astrid
