### ISSUE TITLE
Tarea 3: Análisis a nivel de pacientes o visitas

### ISSUE THREAD

**Issue by JuaniAndres** [IIC2433/Syllabus-2020-2#89]
Hola una duda que no estoy seguro si la idea es que hagamos la tarea analizando a nivel de visitas ósea considerando cada fila del dataset como independiente (dejar fuera el patient_nbr) o si la idea es que sea a nivel de pacientes que en ese caso como hay algunos pacientes que tienen varias visitas se tendría que optar por dejar una sola visita. En el primer caso considerando a nivel de visitas se tendrían algunas fila que están relacionadas (mismos atributos relacionados con el paciente) por lo que no se si eso se considera malo para lo que se pide en la tarea.
Gracias de antemano por la respuesta

**Comment by AstridESMJ** [comment]
Hola!
Te recomiendo que analices ambos escenarios y veas con cuál podrías responder las preguntas que se realizan, o acercarte a responderla. El análisis del dataset es parte de la tarea que deben realizar y justificar las toma de decisiones.

Saludos,

Astrid
