### ISSUE TITLE
Consultas T1

### ISSUE THREAD

**Issue by cristian-vallejos** [IIC2433/Syllabus-2020-2#9]
Haciendo la tarea, me aparecieron las siguientes consultas:

1. En la tarea, se puede agregar parámetros a los métodos especificados en el enunciado para la clase **fpgrowth**? (p.e. _self_)
2. Al ordenar las frecuencias de las películas en el dataset, hay que ordenar de manera ascendente o descendente los ids cuando las frecuencias son iguales? O da lo mismo?

**Comment by Jiruiz2** [comment]
Hola,

Sobre tus preguntas:
1. Si, no hay problema con eso
2. El criterio lo defines tú.

Saludos

**Comment by FloValdes** [comment]
Hola, tengo una duda sobre la parte que dice que el árbol debe ser generado recursivamente. A qué se refiere exactamente? El algoritmo que vimos en la ayudantía iteraba sobre los sets de items de los usuarios, debemos pensar en una nueva manera de hacer lo mismo pero con recursión? Gracias.
