### ISSUE TITLE
Cálculo del centroide

### ISSUE THREAD

**Issue by mathiasvaldebenito** [IIC2433/Syllabus-2020-2#91]
Para calcular un punto representativo del Cluster se dice que es 'el promedio de todos los puntos que hay en el cluster', esto es promedio por componente? Por ejemplo, en el caso donde tenemos que utilizar el dataset original tendremos puntos con n dimensiones: C_1 = (a_1.1, a_1.2, a_1.3, ..., a_1.n),  C_2  = (a_2.1, a_2.2, a_2.3, ..., a_2.n), etc. Si tenemos x puntos entonces el cálculo sería de la forma: R = (( a_1.1 + a_2.1 + a_3.1 + ... + a_x.1))/ x , ( a_1.2 + a_2.2 + a_3.2 + ... + a_x.2))/ x, ..., ( a_1.n + a_2.n + a_3.n + ... + a_x.n))/ x ?

**Comment by AstridESMJ** [comment]
Hola!
Es simplemente el promedio de los componentes que contiene el cluster, acorde a cómo se va generando los clusters jerárquicamente. Puedes revisar la ayudantía y las referencias en el enunciado para mayor detalle.

Saludos,

Astrid
