### ISSUE TITLE
Control 6, parte 1: definir distancia

### ISSUE THREAD

**Issue by lucas-valenzuela** [IIC2433/Syllabus-2020-2#92]
Hola, dado que no se especifica, podemos elegir arbitrariamente qué distancia utilizar para K-Means, por ejemplo, euclidiana o manhattan?
Saludos

**Comment by sricke** [comment]
Se ocupa la distancia euclidiana. Acabo de subir la issue con todas las dudas frecuentes del control para que la revises si tienes más dudas.
