### ISSUE TITLE
Dudas Control 6

### ISSUE THREAD

**Issue by sricke** [IIC2433/Syllabus-2020-2#93]
# Control 06: Dudas Frecuentes

## General

1. Lo entregado debe ser un PDF. Puede ser hecho a mano, foto, scanner, pero **debe** ser PDF.

2. ¿Se puede mezclar partes hechas a mano y otras en PC, Escaneando las partes a mano? Si, mientras al final entregas un PDF, se entienda todo y sea algo que hiciste tu.

## Pregunta álgoritmo de clustering

1. En la pregunta 1.1 y 1.2 se ocupa distancia euclidiana
2. En la pregunta 1.1 por medias iniciales se refiere a los centroides de cada cluster para iniciar el algoritmo.
3. En la pregunta 1.1 no es necesario realizar todos los cálculos de distancia de los puntos a los centroides, siempre y cuando se ejecuten los pasos correctamente, es decir, al inicio de la iteración están la cantidad de puntos adecuadas. 

## Pregunta GMM

1. En la pregunta 2.2 Cuando dice dos posibles clusters se refiere a dos configuraciones distintas de clusters para diferentes ejecuciones, sobre el **MISMO** dataset.

## Pregunta Evaluación de Clustering

1. En la pregunta 3.2 por diferente configuración del mismo algoritmo se refiere a por ejemplo cambiar los hiperparámetros de este.
2. En la pregunta 3.3 sólo se aceptan dibujos, no imágenes obtenidas de internet. Estos pueden ser a mano, con paint, etc.
3. En la pregunta 3.3 cuando dice de no existir patrones, se refiere a que sabemos que no existen patrones. Y el objetivo sigue siendo de clasificación pero no necesariamente con el uso de clustering.  
4. En la pregunta 3.3 los datos no tienen label.

## Bonus 

Pueden subir un zip con el pdf y la imagen o la imagen en el pdf mismo. Se evaluará un **SOLO** meme, en caso de ser más, expliciten cuál quieren que sea evaluado.

**Comment by pazanelli** [comment]
En la pregunta 3.1, ¿puedo poner dos problemas que corresponden a extremos distintos pero del mismo criterio?. Me refiero a: 'un problema sería que fuera excesivamente azul' y 'otro problema sería que fuera muy poco azul'. ¿O tienen que ser criterios distintos?

**Comment by danustilovsky** [comment]
Hola, en la pregunta 1.1 podemos aproximar a numero enteros las posiciones de los centroides para facilitar el calculo de las distancias? Y en caso de empate en las distancias, hay algun criterio para alegir? 

Ademas, en la 1.2, si estoy moviendo el producto 1, su posicion se coincidera como parte de la vecindad o se ignora?
Gracias!

**Comment by sricke** [comment]
@pazanelli No entendi muy bien tu duda. En clases se vieron varias razones para validar los resultados de clustering, ojalá eso te guíe en esa pregunta!

**Comment by fguinez** [comment]
Hola! En la 1.1 podemos elegir el criterio que queramos en caso de encontrarnos con un cluster vacío?

Por ejemplo, simplemente eliminar el centroide correspondiente.

**Comment by sricke** [comment]
@danustilovsky Buena pregunta. Para estandarizar las respuestas decidimos que en caso de empate eligan el cluster actual. Si ya respondieron la pregunta de otra forma basta con una justificación. Y con respecto a los números deben trabajar con un decimal porque las distancias son chicas. Saludos!

**Comment by sacorsi** [comment]
Hola! Tengo la misma duda que @danustilovsky en la 1.2. Para la vecindad de un punto, tenemos que considerar este punto para el calculo de la media??

**Comment by sricke** [comment]
@fguinez En dicho caso el centroide se mantiene en la posición de la iteración anterior y se queda sin datos. No se elimina. Saludos!

**Comment by lucasmarinb** [comment]
Lo estoy haciendo en formato digital, ¿el dibujo de la 3 lo puedo hacer en draw.io o paint?

**Comment by sricke** [comment]
@lucasmarinb Sí se puede hacer con esas herramientas, la idea es que lo hagan ustedes y no descarguen una imagen de alguna parte.

**Comment by sricke** [comment]
@sacorsi @danustilovsky El centroide no es parte del dataset por lo que no se toma en cuenta para el calculo de la media de la vecindad, sólo es un punto de referencia para encontrar los puntos más cercanos.

**Comment by arpincheira** [comment]
@sricke pero cuando inicia la ejecución del algoritmo el centroide a considerar si es un punto del Dataset, en ese caso se toma o se ignora también?

**Comment by jcechavarri** [comment]
En la pregunta 1.2, en caso de llegar a un punto que está dentro de 2 vecindades, que resolución se toma?

**Comment by pazanelli** [comment]
En la pregunta 3.2, con error se refiere a indicar un posible error al usar, por ejemplo, un algoritmo particular de clustering?, o a un caso en que sea inadecuado usar clustering sin importar qué algoritmo

**Comment by sricke** [comment]
@arpincheira Si, en la primera iteracion el primer dato seria el centroide por lo que se considera, pero luego este se va moviendo y se considera solo de alrededor

**Comment by sricke** [comment]
@pazanelli A lo segundo, un caso que sea inadecuado utilizar clustering
