### ISSUE TITLE
T3 - Parámetros función preprocesamiento

### ISSUE THREAD

**Issue by fguinez** [IIC2433/Syllabus-2020-2#94]
Hola! En el enunciado dice:

> ...deberás crear una función llamada `preprocesamiento` que se encargue de **abrir el dataset con pandas** y limpiar los datos según la descripción de la tabla 1...

¿Esto significa que la función `preprocesamiento` debe recibir como parámetro un string con el path del dataset? ¿O podemos pasarle como parámetro un objeto `pd.DataFrame`?

**Comment by vvcastro** [comment]
Hola!

La función debe recibir como parámetro el ```path``` al dataset.
