### ISSUE TITLE
Promedio Tareas

### ISSUE THREAD

**Issue by cristian-vallejos** [IIC2433/Syllabus-2020-2#95]
Buenas,

Redacto esta issue con el fin de consultar lo siguiente. Si mi promedio de tareas fuese 3,8 (asumiendo una nota 1,0 en la Tarea 3) y mi promedio de actividades es 6,0, ¿cuál de los siguientes dos escenarios es el que se cumple?:

- Repruebo las tareas con 3,8 (_promedio entre las 3 tareas_).
- Apruebo las tareas con 4,3 (_promedio entre T1, T2, T3 y AF_).

¡Gracias de antemano!

**Comment by Hernan4444** [comment]
Hola,

Aprobarías con 4,3. Primero se calcula la nota final de tareas considerando las actividades (en caso que te suba) y luego se aplica el criterio de reprobar si dicha nota es menor a 3.95

Saludos :v:

**Comment by cristian-vallejos** [comment]
¡Muchas gracias, Hernán!
