### ISSUE TITLE
[Tarea 3] - Sobre la columna weight

### ISSUE THREAD

**Issue by VicenteVicente** [IIC2433/Syllabus-2020-2#96]
Hola, he decidido botar la columna weight porque mas de 90% de los datos son "?". El problema que me ocurre es que al final quedo como con ~30000 datos y mi algoritmo nunca termina. ¿Debería botar por filas los "?" en vez de la columna weight entera para tener una cantidad de datos razonable para el algoritmo? Ya vi la ayudantía pero no quede muy claro :cry:

**Comment by mpbascunan** [comment]
Tengo la misma duda:c

**Comment by AstridESMJ** [comment]
¡Hola!,

La decisiones en el preprocesamiento de los datos debe ser tomada por cada uno de ustedes y deben explicarlas según las preguntas de la tarea.
Si tienen problemas con los tiempos de entrenamiento muy largos, como hemos visto en las ayudantías, deben realizar subsampling. Deben tomar muestras aleatorias del dataset usando por ejemplo la función de pandas _sample_.
El número de muestras dependerá de la capacidad computacional que tengan.

Saludos,

Astrid

**Comment by mpbascunan** [comment]
Entonces, no hay sólo un preprocesamiento correcto? sino que dependen de lo razonable de la justificación?

**Comment by agustin-rios** [comment]
En la pagina de donde sacaron los datos hay un analisis profundo de estos mismos, a mi me ayudo bastante de hecho para el preprocesamiento y te recomiendo leerlo.

**Comment by AstridESMJ** [comment]
¡Hola!

El preprocesamiento es una de las etapas de minería de datos más importante, y ésta esta íntimamente ligada a los datos y el contexto en el que estamos trabajando. De aquí se desprende que deben realizar un razonamiento sobre cuál es la mejor solución para el preprocesamiento, usando lo aprendido en el curso.
Pueden ver el análisis de la página mencionada pero en las respuestas que entreguen en la tarea debe ser un análisis personal y no usando como cita la página, deben ustedes explicar en sus palabras por qué tomaron esas decisiones.

Saludos,

Astrid

**Comment by VicenteVicente** [comment]
Osea sería válido decir: Preferí botar weight por filas que por columnas, porque en el caso contrario mi algoritmo no termina?

**Comment by AstridESMJ** [comment]
Si la razón es porque tu algoritmo no termina, no es correcto, esa no es una razón para hacer eliminación por filas.
Deben hacer un análisis profundo del dataset y las razones para eliminar datos deben estar bien justificadas.
Si la capacidad computacional no te permite procesar todos los datos debes entonces hacer una submuestra aleatoria, eso es distinto a hacer eliminación de filas en el preprocesamiento.

Saludos,

Astrid

**Comment by VicenteVicente** [comment]
Muchas gracias por la recomendación 😃
