### ISSUE TITLE
T3 - Tiempo construcción matríz de distancias

### ISSUE THREAD

**Issue by fguinez** [IIC2433/Syllabus-2020-2#97]
¿Hay alguna estimación de cúanto debería demorar en construirse la matriz de distancia? Como su construcción es _O(n^2)_ se me está demorando muchísimo.

Truncando el dataset a diferentes tamaños tengo esto:
```
Datos   Tiempo
100     1.99s
200     8.34s
1000    3.3m
50000   5.7 días    (estimado)
100000  22.7 días   (estimado)
```

Por la limpieza que hay que hacer al dataset en ningún caso creo que llegue a 100.000, pero hasta ahora probando diferentes condiciones solo he logrado reducir el dataset a aproximadamente 50.000 filas, lo que sigue implicando mucho tiempo de ejecución.

Entonces, no sé si debo seguir optimizando la construcción (ya no se me ocurre como😢) o realmente el dataset se debe reducir mucho más de lo que ya lo estoy reduciendo.

**Comment by Pipelao** [comment]
Hola,

La verdad es que ni siquiera he llegado a esa parte, estoy haciendo el preprocesamiento, xD. Pero en el video de la ayudantía nos hicieron notar que la matriz es simétrica, ¿eso ayudará en algo en bajar el tiempo de construcción de la matriz?

Saludos.

PD: No soy ayudante.

**Comment by fguinez** [comment]
Hola! Sii eso ayuda bastante, reduce el tiempo casi a la mitad. Pero ya está considerado en los tiempos de ejecución que mostré🙁

**Comment by JuaniAndres** [comment]
Yo tengo el mismo problema, no se si algún ayudante nos puede dar una pista de con cuantas filas aproximadamente deberíamos terminar después del preprocesamiento o si podemos trabajar con una parte de los datos para que no se extienda tanto el calculo de la matriz.

**Comment by szabala** [comment]
Sumando a esto, con 100000 filas no da ni la memoria para la matriz de distancia:

![image](https://user-images.githubusercontent.com/48331715/100523142-ec070e80-318c-11eb-996a-d2025396fe22.png)

**Comment by AstridESMJ** [comment]
¡Hola!,

Para abordar problemas con los tiempos de entrenamiento, como hemos visto en las ayudantías, deben realizar subsampling. Deben tomar muestras aleatorias del dataset usando por ejemplo la función de pandas _sample_.
El número de muestras dependerá de la capacidad computacional que tengan.
Las muestras deben ser aleatorias y no truncar el dataset en las primeras filas porque podrías estar incorporando sesgos si el dataset está ordenado de alguna forma, deben cuidar esos pasos.

Saludos,

Astrid

**Comment by JuaniAndres** [comment]
Yap una duda astrid la idea es tomar una muestra aleatoria y entregarle eso al fit_predict o se le entrega al fit_predict todos los datos y en esa parte se separa/trabaja por grupos?

**Comment by AstridESMJ** [comment]
¡Hola!,

No sé si te entiendo bien, pero la submuestra sirve para hacer el entrenamiento y predicción y que no se demore tanto por problemas de capacidad computacional. Es decir la sub-muestra la usas en el fit_predict.

Saludos,

Astrid

**Comment by JuaniAndres** [comment]
Ya me quedo más claro 
gracias Astrid
