### ISSUE TITLE
T3- duda PCA

### ISSUE THREAD

**Issue by mgbriones** [IIC2433/Syllabus-2020-2#98]
Hola no me queda muy claro en que momento de la tarea debemos hacer PCA, antes o despues de obtener los cluster?
Me confunde por que en el enunciado dice que en la funcion de preprocesamiento esta permitido usar sklearn para la reduccion de dimensionalidad.

**Comment by Hernan4444** [comment]
Hola,

Es en ambos casos. Porque son 2 experimentos:
1. Tomas tu dataset preprocesado (luego de eliminar columnas y/o filas de forma justificada), calculas los clusters, aplicas reducción de dimensión para obtener 2 dimensiones y visualizas en función de esas 2 dimensiones. Aquí puedes ver que los clusters se calcularon en función de tu dataset sin reducir dimensión.

2. Tomas tu dataset preprocesado (luego de eliminar columnas y/o filas de forma justificada), reduces la dimensión a 2 columnas, calculas los clusters y visualizas. Aquí puedes ver que los clusters se calcularon en función de tu dataset reducido.

De este modo podemos ver el efecto que tuve PCA en identificar clusters.

Saludos :v:

**Comment by mgbriones** [comment]
:raised_hands:  Aaaa perfecto, resolvi muchas dudas con eso, gracias!
