### ISSUE TITLE
t3- metodos pedidos 

### ISSUE THREAD

**Issue by mgbriones** [IIC2433/Syllabus-2020-2#99]
Hola un par de dudas:
1-no me queda muy claro que se supone que debe retornar el metodo **fit-**predict****, ¿podria ser una lista , tuplas , etc, que contenga los cluster??

2-El metodo **condensed_distance_matrix** debe retornar la ultima matriz  de distancias?

**Comment by AstridESMJ** [comment]
¡Hola!

Como dice en el enunciado:
fit_predict 
- > recibe una matriz de distancias vacía y, según los atributos de linkage y métrica de distancia, ir llenando esta matriz.  
- > retorna los labels o clusters asociados a cada dato.  
El formato de salida debes elegirlo tu.

Como dice el enunciado desde la matriz de distancia **computada** se genera la matriz condensada:
->  Una matriz condensada de distancias es el triangulo superior derecho de la matriz de distancia agrupado como un vector de una dimensión.

Saludos,

Astrid
